import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
import {createCuteChildAvatar,createCuteDog,createCuteCat,animateCuteCharacter,setCuteCharacterPose,normalizeAvatarCustomization} from './character-models.js?v=0.4.55-arm-jump';
import {createCow,createSheep,createChicken,animateAnimal} from './animal-models.js';
import {createCropModel,createFruitTreeModel} from './crop-models.js';
import {createEconomyState,addInventory,shipAllSellable,settleShipping,buyShopItem,SHOP_ITEMS,ITEM_NAMES,pendingShippingValue,ownedCount} from './economy-system.js';
import {getFurnitureInteraction,furnitureAnchorWorld,furnitureExitWorld,furnitureYaw,isFurnitureInteractable} from './furniture-interaction.js';
import {advanceDailyRecord} from './daily-progression-system.js';

const VERSION='V0.4.55',WORLD_SIZE=180,HALF=WORLD_SIZE/2,FARM_YAW=-.72,FARM_DISTANCE_MIN=3.8,FARM_DISTANCE_DEFAULT=6.8,THIRD_CAMERA_DISTANCE=3.8,CAMERA_TUNING_REVISION=1;
const versionBadge=document.querySelector('.title small');if(versionBadge)versionBadge.textContent=VERSION;const versionNote=document.querySelector('.note');if(versionNote)versionNote.textContent=versionNote.textContent.replace(/^V0\.4\.\d+：/,`${VERSION}：`);
const SAVE_KEY='ag_cute_blocks_world_v04',OLD_SAVE_KEY='ag_cute_blocks_world_v03',SETTINGS_KEY='ag_cute_blocks_settings_v03',CARE_KEY='ag_cute_blocks_crop_care_v1';
const $=s=>document.querySelector(s);
const ui={status:$('#status'),cats:$('#cats'),items:$('#items'),cam:$('#cam'),admin:$('#admin'),panel:$('#adminPanel'),season:$('#season'),weather:$('#weather'),timeSpeed:$('#timeSpeed'),avatar:$('#avatar'),avatarAge:$('#avatarAge'),avatarBody:$('#avatarBody'),avatarSkin:$('#avatarSkin'),avatarHairStyle:$('#avatarHairStyle'),avatarHair:$('#avatarHair'),avatarOutfit:$('#avatarOutfit'),avatarTop:$('#avatarTop'),avatarBottom:$('#avatarBottom'),avatarHat:$('#avatarHat'),avatarGlasses:$('#avatarGlasses'),avatarAccessory:$('#avatarAccessory'),save:$('#saveNow'),closeAdmin:$('#closeAdminFloat'),add:$('#add'),del:$('#del'),jump:$('#jump'),rot:$('#rot'),joy:$('#joy'),knob:$('#knob'),clock:$('#clock')};

function installLifeUI(){const style=document.createElement('style');style.textContent=`.lifeInteract{position:fixed;z-index:75;right:max(72px,calc(env(safe-area-inset-right) + 66px));bottom:max(148px,calc(env(safe-area-inset-bottom) + 138px));width:62px;height:62px;border:0;border-radius:50%;background:#fff7cce8;box-shadow:0 3px 12px #0003;font-size:24px;font-weight:900;color:#42565c;pointer-events:auto}.lifeInteract small{display:block;font-size:8px}.lifeBtn{position:fixed;z-index:75;right:max(10px,env(safe-area-inset-right));top:max(47px,calc(env(safe-area-inset-top) + 40px));border:0;border-radius:13px;background:#fffde8e8;padding:7px 9px;font-size:12px;font-weight:900;pointer-events:auto}.lifePanel{position:fixed;z-index:95;left:0;top:0;height:100dvh;width:min(390px,94vw);background:#fffaf0f7;transform:translateX(-108%);transition:.22s;pointer-events:auto;overflow:auto;padding:max(16px,env(safe-area-inset-top)) 14px max(18px,env(safe-area-inset-bottom));color:#3d5556}.lifePanel.open{transform:translateX(0)}.lifeClose{position:absolute;right:12px;top:10px;width:36px;height:36px;border:0;border-radius:50%;background:#fff;font-size:18px}.lifePanel h2{margin:4px 42px 8px 0}.lifeSummary{display:flex;gap:7px;flex-wrap:wrap}.lifeChip,.lifeSection{background:#fff;border-radius:13px;padding:9px;margin:7px 0}.invRow,.shopRow{display:grid;grid-template-columns:1fr auto;gap:8px;padding:7px 0;border-bottom:1px solid #0001;font-size:12px}.buyBtn{border:0;border-radius:9px;background:#ffe98b;padding:7px 9px;font-weight:800}.buyBtn:disabled{background:#eee;color:#999}@media(max-height:430px){.lifeInteract{width:54px;height:54px;right:64px;bottom:132px}.lifeBtn{top:40px}}`;document.head.appendChild(style);const w=document.createElement('div');w.innerHTML=`<button id="lifeInteract" class="lifeInteract">✨<small>互動</small></button><button id="lifeBtn" class="lifeBtn">🎒 生活</button><button id="lifeCloseFloat" class="panelCloseFloat" aria-label="關閉生活面板">×</button><aside id="lifePanel" class="lifePanel"><h2>🎒 生活小屋</h2><div class="lifeSummary"><div id="coinChip" class="lifeChip">🪙 0</div><div id="shipChip" class="lifeChip">📦 0</div></div><section class="lifeSection"><h3>背包</h3><div id="inventoryList"></div></section><section class="lifeSection"><h3>小商城</h3><div id="shopList"></div></section></aside>`;document.body.appendChild(w);return{interact:$('#lifeInteract'),btn:$('#lifeBtn'),panel:$('#lifePanel'),close:$('#lifeCloseFloat'),coins:$('#coinChip'),shipping:$('#shipChip'),inventory:$('#inventoryList'),shop:$('#shopList')}}
const lifeUI=installLifeUI();

const scene=new THREE.Scene();scene.background=new THREE.Color(0x9ed9ff);scene.fog=new THREE.Fog(0x9ed9ff,62,170);
const camera=new THREE.PerspectiveCamera(68,innerWidth/innerHeight,.1,260);const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;document.body.prepend(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xfff5d8,0x6e9864,2.15));const sun=new THREE.DirectionalLight(0xffffff,2);sun.position.set(45,70,25);sun.castShadow=true;scene.add(sun);const moon=new THREE.DirectionalLight(0xb8c8ff,0);scene.add(moon);
const lm=c=>new THREE.MeshLambertMaterial({color:c});const mats={grass:lm(0x8fd47b),wood:lm(0xc99b68),darkwood:lm(0x805a43),stone:lm(0xaab0b6),marble:lm(0xe9e7e2),brick:lm(0xc97868),concrete:lm(0xc7cbce),white:lm(0xf7f4ed),pink:lm(0xf4a6b8),blue:lm(0x90c8ee),yellow:lm(0xf3d477),roof:lm(0xb86f58),soil:lm(0x79563b),metal:new THREE.MeshPhongMaterial({color:0x9da4aa,shininess:80}),glass:new THREE.MeshPhongMaterial({color:0xa8e8f3,transparent:true,opacity:.48,shininess:90,side:THREE.DoubleSide}),water:new THREE.MeshPhongMaterial({color:0x4fb7df,transparent:true,opacity:.73,shininess:100})};
const world=new THREE.Group();scene.add(world);const groundMat=mats.grass.clone(),ground=new THREE.Mesh(new THREE.PlaneGeometry(WORLD_SIZE,WORLD_SIZE),groundMat);ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;ground.userData.ground=true;world.add(ground);const grid=new THREE.GridHelper(WORLD_SIZE,WORLD_SIZE,0x679b5f,0x7abb70);grid.position.y=.008;grid.material.opacity=.13;grid.material.transparent=true;world.add(grid);
const waterMeshes=[];const river=new THREE.Mesh(new THREE.PlaneGeometry(14,145),mats.water);river.rotation.x=-Math.PI/2;river.rotation.z=.1;river.position.set(-38,.035,3);world.add(river);waterMeshes.push(river);const lake=new THREE.Mesh(new THREE.CircleGeometry(18,48),mats.water);lake.rotation.x=-Math.PI/2;lake.position.set(42,.04,-38);lake.scale.set(1.35,.78,1);world.add(lake);waterMeshes.push(lake);const buildAimTargets=[ground,river,lake],buildAimTargetSet=new Set(buildAimTargets);function registerBuildAimTarget(root){if(root&&!buildAimTargetSet.has(root)){buildAimTargetSet.add(root);buildAimTargets.push(root)}}function unregisterBuildAimTarget(root){if(!root||!buildAimTargetSet.delete(root))return;const i=buildAimTargets.indexOf(root);if(i>=0)buildAimTargets.splice(i,1)}
const wetGroundGroup=new THREE.Group();wetGroundGroup.name='agcb-wet-ground';world.add(wetGroundGroup);
const puddleGeometry=new THREE.CircleGeometry(1,16),puddleMaterial=new THREE.MeshPhongMaterial({color:0x9bc9c5,transparent:true,opacity:.24,shininess:110,depthWrite:false});let wetGroundState='';
function refreshWetGround(){const kind=weather==='rain'||weather==='thunderstorm'?weather:'dry',tier=globalThis.__AGCB_PERF_TIER||'normal',signature=kind+'/'+tier;if(signature===wetGroundState)return;wetGroundGroup.clear();wetGroundState=signature;if(kind==='dry')return;const count=tier==='high'?16:tier==='low'?5:10;puddleMaterial.opacity=kind==='thunderstorm'?.29:.23;for(let i=0,used=0;i<48&&used<count;i++){const x=((i*37)%160)-80,z=((i*61+17)%160)-80;if(inWater(x,z))continue;const p=new THREE.Mesh(puddleGeometry,puddleMaterial);p.rotation.x=-Math.PI/2;p.position.set(x,.026,z);const sx=.55+(i%5)*.16,sz=.34+(i%4)*.12;p.scale.set(sx,sz,1);p.userData={wetGround:true,solid:false};wetGroundGroup.add(p);used++}}
const CHUNK_SIZE=32,WORLD_INDEX_KEY='ag_cute_blocks_world_index_v1',WORLD_PARTITIONS=['terrain','buildings','objects','farms','animals','players'];const worldIndex={schema:2,worldId:'ag-local-world',chunkSize:CHUNK_SIZE,partitions:WORLD_PARTITIONS,chunks:{},entities:{},dirtyChunks:{},dirtyEntities:{}};
function worldChunkKey(x,z){return `${Math.floor(x/CHUNK_SIZE)},${Math.floor(z/CHUNK_SIZE)}`}
function worldPartitionFor(root,kind){const u=root?.userData||{};if(kind==='terrain'||u.ground||u.terrain)return'terrain';if(kind==='player'||u.entityId==='player-local')return'players';if(u.crop||u.treeKind)return'farms';if(u.ranch||u.pet||u.wildlife)return'animals';if(kind==='building')return'buildings';return'objects'}
function markWorldIndexDirty(id,chunk){if(chunk)worldIndex.dirtyChunks[chunk]=true;if(id)worldIndex.dirtyEntities[id]=true}
function ensureWorldChunk(chunk){let c=worldIndex.chunks[chunk];if(!c||Array.isArray(c)){const next={};for(const p of WORLD_PARTITIONS)next[p]=[];if(Array.isArray(c)&&c.length)next.objects.push(...c);worldIndex.chunks[chunk]=c=next}else for(const p of WORLD_PARTITIONS)if(!Array.isArray(c[p]))c[p]=[];return c}
function removeWorldEntityFromChunk(id,chunk,partition){const c=worldIndex.chunks[chunk];if(!c)return;const parts=partition?[partition]:WORLD_PARTITIONS;for(const p of parts){const list=c[p];if(!Array.isArray(list))continue;const i=list.indexOf(id);if(i>=0)list.splice(i,1)}if(WORLD_PARTITIONS.every(p=>!(c[p]?.length)))delete worldIndex.chunks[chunk]}
function registerWorldEntity(root,kind){const id=root?.userData?.id||root?.userData?.entityId;if(!id)return;const chunk=worldChunkKey(root.position.x,root.position.z),partition=worldPartitionFor(root,kind),previous=worldIndex.entities[id];if(previous&&(previous.chunk!==chunk||previous.partition!==partition))removeWorldEntityFromChunk(id,previous.chunk,previous.partition);worldIndex.entities[id]={id,kind,partition,type:root.userData.type||root.userData.kind,chunk,x:root.position.x,z:root.position.z};const list=ensureWorldChunk(chunk)[partition];if(!list.includes(id))list.push(id);markWorldIndexDirty(id,chunk);if(previous&&(previous.chunk!==chunk||previous.partition!==partition))markWorldIndexDirty(id,previous.chunk)}
function updateWorldEntity(root){const id=root?.userData?.id||root?.userData?.entityId;if(!id)return;const next=worldChunkKey(root.position.x,root.position.z),record=worldIndex.entities[id],partition=worldPartitionFor(root,record?.kind||root.userData.kind);if(!record){registerWorldEntity(root,root.userData.type||root.userData.kind);return}record.x=root.position.x;record.z=root.position.z;if(record.chunk===next&&record.partition===partition)return;removeWorldEntityFromChunk(id,record.chunk,record.partition);markWorldIndexDirty(id,record.chunk);record.chunk=next;record.partition=partition;const list=ensureWorldChunk(next)[partition];if(!list.includes(id))list.push(id);markWorldIndexDirty(id,next)}
function unregisterWorldEntity(root){const id=root?.userData?.id||root?.userData?.entityId,record=id&&worldIndex.entities[id];if(!record)return;removeWorldEntityFromChunk(id,record.chunk,record.partition);markWorldIndexDirty(id,record.chunk);delete worldIndex.entities[id];delete worldIndex.dirtyEntities[id]}
function saveWorldIndex(){localStorage.setItem(WORLD_INDEX_KEY,JSON.stringify({schema:worldIndex.schema,worldId:worldIndex.worldId,chunkSize:worldIndex.chunkSize,partitions:worldIndex.partitions,chunks:worldIndex.chunks,entities:worldIndex.entities,savedAt:Date.now()}));worldIndex.dirtyChunks={};worldIndex.dirtyEntities={}}
for(const [root,entityId] of [[ground,'terrain-ground'],[river,'terrain-river'],[lake,'terrain-lake']]){root.userData.entityId=entityId;registerWorldEntity(root,'terrain')}
const plotCenters=[[-58,-30],[-58,28],[-4,-54],[-2,53],[52,-8],[55,48]];for(const [i,p] of plotCenters.entries()){const pad=new THREE.Mesh(new THREE.PlaneGeometry(34,30),lm(i%2?0x96d483:0x9cda89));pad.material.transparent=true;pad.material.opacity=.38;pad.rotation.x=-Math.PI/2;pad.position.set(p[0],.012,p[1]);pad.userData.homestead=i+1;world.add(pad)}
const blocks=new Map(),objects=[],ranch=[],pets=[],cameraTargets=[],cameraTargetSet=new Set();
const SOLID_CELL=4,solidGrid=new Map(),solidCells=new WeakMap(),solidIndexBox=new THREE.Box3();
const INTERACTION_CELL=4,interactionGrid=new Map(),interactionCells=new WeakMap(),interactionNearby=[];let changed=false,settings={};try{settings=JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}')}catch{}
let season=settings.season||'spring',weather=settings.weather||'sunny',timeSpeed=Number(settings.timeSpeed||1),simMinutes=settings.simMinutes??480,worldDay=Number(settings.worldDay||1),economy=createEconomyState(settings.economy||{}),cameraTuningNeedsMigration=settings.cameraTuningRevision!==CAMERA_TUNING_REVISION;settings.cameraTuningRevision=CAMERA_TUNING_REVISION;let farmDistance=Math.max(FARM_DISTANCE_MIN,Math.min(15.5,cameraTuningNeedsMigration?FARM_DISTANCE_DEFAULT:Number(settings.farmDistance)||FARM_DISTANCE_DEFAULT)),farmPitch=Math.max(.42,Math.min(1.12,Number(settings.farmPitch)||.64)),farmYaw=Number.isFinite(Number(settings.farmYaw))?Number(settings.farmYaw):FARM_YAW;
function registerCameraMesh(m){if(m?.isMesh&&!cameraTargetSet.has(m)){cameraTargetSet.add(m);cameraTargets.push(m)}}
function registerCameraTarget(root){if(root?.isMesh)registerCameraMesh(root);else root?.traverse?.(registerCameraMesh)}
function unregisterCameraTarget(root){const drop=m=>{if(!m?.isMesh||!cameraTargetSet.delete(m))return;const i=cameraTargets.indexOf(m);if(i>=0)cameraTargets.splice(i,1)};if(root?.isMesh)drop(root);else root?.traverse?.(drop)}
function solidCellKey(cx,cz){return cx*4096+cz}
function unregisterSolid(root){const keys=solidCells.get(root);if(!keys)return;for(const key of keys){const bucket=solidGrid.get(key);if(!bucket)continue;bucket.delete(root);if(!bucket.size)solidGrid.delete(key)}solidCells.delete(root)}
function registerSolid(root,pad=root?.userData?.kind==='block'?.24:.22){if(!root?.userData?.solid&&root?.userData?.kind!=='block')return;unregisterSolid(root);root.updateMatrixWorld(true);solidIndexBox.setFromObject(root).expandByScalar(pad);const minX=Math.floor(solidIndexBox.min.x/SOLID_CELL),maxX=Math.floor(solidIndexBox.max.x/SOLID_CELL),minZ=Math.floor(solidIndexBox.min.z/SOLID_CELL),maxZ=Math.floor(solidIndexBox.max.z/SOLID_CELL),keys=[];for(let cx=minX;cx<=maxX;cx++)for(let cz=minZ;cz<=maxZ;cz++){const key=solidCellKey(cx,cz);let bucket=solidGrid.get(key);if(!bucket)solidGrid.set(key,bucket=new Set());bucket.add(root);keys.push(key)}solidCells.set(root,keys);root.userData.collisionPad=pad}
function reindexSolid(root){registerSolid(root,root?.userData?.collisionPad??(root?.userData?.kind==='block'?.24:.22))}
function interactionCellKey(cx,cz){return cx*4096+cz}
function isInteractionCandidate(root){const u=root?.userData||{};return isFurnitureInteractable(u.type)||!!(u.crop||u.treeKind||u.shippingBox||u.ranch||u.pet)}
function unregisterInteractionTarget(root){const key=interactionCells.get(root);if(key===undefined)return;const bucket=interactionGrid.get(key);if(bucket){bucket.delete(root);if(!bucket.size)interactionGrid.delete(key)}interactionCells.delete(root)}
function registerInteractionTarget(root){if(!isInteractionCandidate(root))return;unregisterInteractionTarget(root);const key=interactionCellKey(Math.floor(root.position.x/INTERACTION_CELL),Math.floor(root.position.z/INTERACTION_CELL));let bucket=interactionGrid.get(key);if(!bucket)interactionGrid.set(key,bucket=new Set());bucket.add(root);interactionCells.set(root,key)}
function updateInteractionTarget(root){if(!isInteractionCandidate(root))return;const next=interactionCellKey(Math.floor(root.position.x/INTERACTION_CELL),Math.floor(root.position.z/INTERACTION_CELL));if(interactionCells.get(root)===next)return;registerInteractionTarget(root)}
function interactionTargetsNear(x,z,radius=2.5){interactionNearby.length=0;const minX=Math.floor((x-radius)/INTERACTION_CELL),maxX=Math.floor((x+radius)/INTERACTION_CELL),minZ=Math.floor((z-radius)/INTERACTION_CELL),maxZ=Math.floor((z+radius)/INTERACTION_CELL);for(let cx=minX;cx<=maxX;cx++)for(let cz=minZ;cz<=maxZ;cz++){const bucket=interactionGrid.get(interactionCellKey(cx,cz));if(bucket)for(const root of bucket)interactionNearby.push(root)}return interactionNearby}
const id=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;function box(g,sx,sy,sz,x,y,z,m='white'){const o=new THREE.Mesh(new THREE.BoxGeometry(sx,sy,sz),typeof m==='number'?lm(m):(mats[m]||mats.white));o.position.set(x,y,z);o.castShadow=o.receiveShadow=true;g.add(o);return o}function sphere(g,r,x,y,z,c,s=[1,1,1]){const o=new THREE.Mesh(new THREE.SphereGeometry(r,16,12),typeof c==='number'?lm(c):(mats[c]||mats.white));o.position.set(x,y,z);o.scale.set(...s);o.castShadow=true;g.add(o);return o}function star(g,rOuter,rInner,depth,x,y,z,color=0xffd95c){const sh=new THREE.Shape();for(let i=0;i<10;i++){const a=-Math.PI/2+i*Math.PI/5,r=i%2?rInner:rOuter,px=Math.cos(a)*r,py=Math.sin(a)*r;i?sh.lineTo(px,py):sh.moveTo(px,py)}sh.closePath();const o=new THREE.Mesh(new THREE.ExtrudeGeometry(sh,{depth,bevelEnabled:false}),lm(color));o.position.set(x,y,z);o.castShadow=true;g.add(o);return o}
function geometryFor(s){if(s==='rect')return new THREE.BoxGeometry(2,1,1);if(s==='cylinder')return new THREE.CylinderGeometry(.5,.5,1,20);if(s==='sphere')return new THREE.SphereGeometry(.58,20,14);if(s==='triangle'){const q=new THREE.Shape();q.moveTo(-.55,-.5);q.lineTo(.55,-.5);q.lineTo(0,.5);q.closePath();const g=new THREE.ExtrudeGeometry(q,{depth:1,bevelEnabled:false});g.translate(0,0,-.5);g.rotateY(Math.PI/2);return g}if(s==='slope'){const q=new THREE.Shape();q.moveTo(-.5,-.5);q.lineTo(.5,-.5);q.lineTo(.5,.5);q.closePath();const g=new THREE.ExtrudeGeometry(q,{depth:1,bevelEnabled:false});g.translate(0,0,-.5);g.rotateY(Math.PI/2);return g}if(s==='roof'){const q=new THREE.Shape();q.moveTo(-.65,-.4);q.lineTo(0,.4);q.lineTo(.65,-.4);q.closePath();const g=new THREE.ExtrudeGeometry(q,{depth:1.4,bevelEnabled:false});g.translate(0,0,-.7);g.rotateY(Math.PI/2);return g}return new THREE.BoxGeometry(1,1,1)}
function addBlock(r){const m=new THREE.Mesh(geometryFor(r.shape||'cube'),mats[r.mat]||mats.wood);m.position.set(r.x,r.y,r.z);m.rotation.y=r.rot||0;m.castShadow=m.receiveShadow=true;m.userData={kind:'block',id:r.id||id(),shape:r.shape||'cube',mat:r.mat||'wood'};world.add(m);blocks.set(m.userData.id,m);registerWorldEntity(m,'building');registerBuildAimTarget(m);registerCameraTarget(m);registerSolid(m,.24);changed=true;return m}
function addObject(r,mark=true){const g=new THREE.Group();g.position.set(r.x||0,0,r.z||0);g.rotation.y=r.rot||0;g.userData={kind:'object',id:r.id||id(),type:r.type,solid:true,growth:r.growth??.2,affection:r.affection??0,lastProductDay:r.lastProductDay??0,productReady:r.productReady};const t=r.type;
if(t==='chair'){box(g,.8,.12,.8,0,.65,0,'wood');for(const X of[-.3,.3])for(const Z of[-.3,.3])box(g,.12,.7,.12,X,.3,Z,'wood');box(g,.8,.78,.12,0,1,-.34,'wood')}
else if(t==='sofa'){box(g,2.2,.55,.9,0,.42,0,0xe98ca0);box(g,2.2,.9,.25,0,.92,.32,0xe98ca0);box(g,.28,.65,.9,-1.08,.55,0,0xe98ca0);box(g,.28,.65,.9,1.08,.55,0,0xe98ca0)}
else if(t==='bed'||t==='starBed'){box(g,2.2,.45,1.45,0,.35,0,'darkwood');box(g,2.05,.3,1.3,0,.65,0,0xfff0d8);box(g,.75,.18,1.1,-.58,.83,0,'white');if(t==='starBed'){box(g,.15,1.2,1.55,-1.08,1.03,0,0x765a8f);star(g,.38,.17,.08,-1.18,1.48,-.04,0xffdb65);star(g,.18,.08,.06,-1.2,1.02,.42,0xfff1a8)}}
else if(t==='petBedRound'){const cushion=new THREE.Mesh(new THREE.CylinderGeometry(.72,.78,.20,28),lm(0xf4b7c6));cushion.position.y=.16;cushion.castShadow=true;g.add(cushion);const rim=new THREE.Mesh(new THREE.TorusGeometry(.72,.14,10,28),lm(0xd9879e));rim.rotation.x=Math.PI/2;rim.position.y=.30;rim.castShadow=true;g.add(rim);sphere(g,.22,-.38,.35,-.48,0xffd4df,[1.05,.55,1.2]);g.userData.solid=false}
else if(t==='cloudLamp'){box(g,.52,.10,.52,0,.05,0,'metal');box(g,.08,1.55,.08,0,.82,0,'metal');const glow=new THREE.MeshPhongMaterial({color:0xfff5cf,emissive:0xffd978,emissiveIntensity:.55});for(const [x,y,s] of[[-.34,1.66,.34],[0,1.78,.43],[.38,1.66,.31],[.1,1.52,.35]]){const c=new THREE.Mesh(new THREE.SphereGeometry(s,16,12),glow);c.position.set(x,y,0);c.scale.z=.72;c.castShadow=false;g.add(c)}g.userData.solid=false}
else if(t==='flowerArch'){const leaf=lm(0x6cad67);for(const X of[-.9,.9]){box(g,.16,2.2,.16,X,1.1,0,'darkwood');for(let y=.42;y<2.12;y+=.38){const l=new THREE.Mesh(new THREE.SphereGeometry(.13,10,8),leaf);l.position.set(X+(y%1>.5?.12:-.12),y,.02);l.scale.set(1.4,.65,.8);g.add(l)}}const arch=new THREE.Mesh(new THREE.TorusGeometry(.9,.10,10,24,Math.PI),lm(0x805a43));arch.rotation.z=Math.PI;arch.position.set(0,2.18,0);g.add(arch);for(const [a,c] of[[.25,0xff91b1],[.65,0xffd36e],[1.05,0xb9a0ee],[1.45,0xff91b1],[1.85,0xffd36e],[2.25,0xb9a0ee],[2.65,0xff91b1]]){const x=Math.cos(a)*.9,y=2.18+Math.sin(a)*.9;for(let p=0;p<5;p++){const q=new THREE.Mesh(new THREE.SphereGeometry(.085,8,6),lm(c));q.position.set(x+Math.cos(p*1.257)*.09,y+Math.sin(p*1.257)*.09,.02);g.add(q)}}g.userData.solid=false}
else if(t==='swingGarden'){for(const X of[-.95,.95])box(g,.12,2.35,.12,X,1.15,0,'darkwood');box(g,2.2,.14,.14,0,2.28,0,'darkwood');for(const X of[-.48,.48])box(g,.025,1.25,.025,X,1.56,.02,0xc5b28e);box(g,1.3,.13,.52,0,.94,.02,'wood')}
else if(t==='table'){box(g,1.8,.14,1.2,0,1,0,'wood');for(const X of[-.72,.72])for(const Z of[-.42,.42])box(g,.12,1,.12,X,.5,Z,'wood')}
else if(t==='cabinet'){box(g,1.6,1.45,.5,0,.72,0,'wood');for(const X of[-.42,.42])box(g,.06,.32,.06,X,.78,-.27,'metal')}
else if(t==='fridge'){box(g,.95,1.9,.85,0,.95,0,0xf2f5f6);box(g,.04,.7,.05,.28,1.35,-.44,'metal')}
else if(t==='washer'){box(g,1,1.05,.85,0,.52,0,'white');const d=new THREE.Mesh(new THREE.CylinderGeometry(.28,.28,.04,24),mats.metal);d.rotation.x=Math.PI/2;d.position.set(0,.48,-.45);g.add(d)}
else if(t==='tv'){box(g,1.7,1,.12,0,1.15,0,0x242a31);box(g,.15,.65,.15,0,.45,.1,'metal');box(g,1,.08,.55,0,.1,.1,'metal')}
else if(t==='stove'){box(g,1.05,.95,.8,0,.48,0,0x55575b);for(const X of[-.25,.25])for(const Z of[-.18,.18]){const p=new THREE.Mesh(new THREE.CylinderGeometry(.11,.11,.02,16),lm(0x202226));p.position.set(X,.97,Z);g.add(p)}}
else if(t==='lamp'){box(g,.12,1.35,.12,0,.7,0,'metal');sphere(g,.32,0,1.5,0,0xffefa8);g.userData.solid=false}
else if(t==='door'){box(g,1.05,2.05,.16,0,1.03,0,'darkwood');sphere(g,.06,.35,1.02,-.1,0xe3c65f)}
else if(t==='window'){box(g,1.5,.12,.12,0,1.35,0,'white');box(g,.12,1.25,.12,-.69,.75,0,'white');box(g,.12,1.25,.12,.69,.75,0,'white');const pane=new THREE.Mesh(new THREE.PlaneGeometry(1.25,1.05),mats.glass);pane.position.set(0,.8,.02);g.add(pane)}
else if(t==='fence'){box(g,2,.12,.12,0,.6,0,'wood');box(g,2,.12,.12,0,1.08,0,'wood');box(g,.14,1.35,.14,-.9,.65,0,'wood');box(g,.14,1.35,.14,.9,.65,0,'wood')}
else if(t==='shippingBox'){box(g,1.55,1.05,1.05,0,.52,0,'wood');g.userData.shippingBox=true}
else if(t==='petDog'||t==='petCat'){const p=t==='petDog'?createCuteDog():createCuteCat();g.add(p);g.userData.solid=false;g.userData.pet=true;g.userData.model=p;pets.push(g)}
else if(['cow','sheep','chicken'].includes(t)){const a=t==='cow'?createCow():t==='sheep'?createSheep():createChicken();g.add(a);g.userData.solid=false;g.userData.ranch=true;g.userData.model=a;g.userData.home=new THREE.Vector2(g.position.x,g.position.z);g.userData.phase=Math.random()*6.28;if(g.userData.productReady===undefined)g.userData.productReady=true;ranch.push(g)}
else if(['carrot','corn','pumpkin','tomato','strawberry','cabbage','potato'].includes(t)){const c=createCropModel(t,g.userData.growth);g.add(c);g.userData.solid=false;g.userData.crop=t;g.userData.model=c}
else if(['appleTree','orangeTree','peachTree'].includes(t)){const k=t.replace('Tree',''),tr=createFruitTreeModel(k,r.growth??1,season);g.add(tr);g.userData.treeKind=k;g.userData.model=tr}
else if(t==='tree'){box(g,.42,2,.42,0,1,0,'wood');sphere(g,1.18,0,2.15,0,0x67ad62,[1,.9,1])}else return null;world.add(g);objects.push(g);registerWorldEntity(g,'object');registerBuildAimTarget(g);registerInteractionTarget(g);if(g.userData.solid){registerCameraTarget(g);registerSolid(g,.22)}if(mark)changed=true;return g}

let avatarCustomization=normalizeAvatarCustomization(settings.avatarCustomization||{},settings.avatar||'girl');function createAvatar(style=avatarCustomization.gender,options=avatarCustomization){return createCuteChildAvatar(style,options)}let player=createAvatar(avatarCustomization.gender,avatarCustomization);player.userData.entityId='player-local';world.add(player);player.position.set(0,0,8);registerWorldEntity(player,'player');
const catalog={'形狀':[['cube','▣','正方體'],['rect','▬','長方體'],['sphere','●','圓形'],['cylinder','⬤','圓柱'],['triangle','▲','三角形'],['slope','◢','斜坡'],['roof','⌂','屋頂塊']],'建材':[['wood','🪵','木材'],['darkwood','🟫','深木'],['stone','🪨','石材'],['marble','◻️','大理石'],['brick','🧱','磚'],['concrete','⬜','混凝土'],['glass','🪟','玻璃'],['roof','🏠','屋瓦'],['pink','🌸','粉色']],'建築':[['door','🚪','門'],['window','🪟','窗'],['fence','🪵','圍欄']],'家具':[['chair','🪑','椅子'],['table','🍽️','桌子'],['sofa','🛋️','沙發'],['bed','🛏️','床'],['lamp','💡','燈']],'家電':[['fridge','🧊','冰箱'],['stove','🍳','爐具'],['washer','🧺','洗衣機'],['tv','📺','電視'],['cabinet','🗄️','櫃子']],'農作':[['carrot','🥕','紅蘿蔔'],['corn','🌽','玉米'],['pumpkin','🎃','南瓜'],['tomato','🍅','番茄'],['strawberry','🍓','草莓'],['cabbage','🥬','高麗菜'],['potato','🥔','馬鈴薯']],'果樹':[['appleTree','🍎','蘋果樹'],['orangeTree','🍊','橘子樹'],['tree','🌳','樹木']],'動物':[['petDog','🐶','小狗'],['petCat','🐱','小貓'],['chicken','🐔','雞'],['cow','🐄','牛'],['sheep','🐑','羊']],'生活':[['shippingBox','📦','出貨箱']]};
const SHOP_BUILD_UNLOCKS={'sapling-peach':['peachTree','🌳','特選桃樹苗'],'pet-bed-round':['petBedRound','🧺','圓圓寵物床'],'lamp-cloud':['cloudLamp','☁️','雲朵燈'],'arch-flower':['flowerArch','🌸','花朵拱門'],'swing-garden':['swingGarden','🌿','花園鞦韆'],'bed-star':['starBed','⭐','星星床']};
let category='形狀',selected='cube',selectedMat='wood',objRot=0,cameraMode=settings.cameraMode||'first';
function syncShopCatalog(){const unlocked=Object.entries(SHOP_BUILD_UNLOCKS).filter(([shopId])=>ownedCount(economy,shopId)>0).map(([,build])=>build);if(unlocked.length)catalog['收藏']=unlocked;else delete catalog['收藏'];if(!catalog[category]?.length){category='形狀';selected='cube'}}
function drawCats(){ui.cats.innerHTML='';Object.keys(catalog).forEach(k=>{const b=document.createElement('button');b.className='cat'+(k===category?' on':'');b.textContent=k;b.onclick=()=>{category=k;selected=k==='建材'?selectedMat:catalog[k][0][0];drawCats();drawItems()};ui.cats.appendChild(b)})}function drawItems(){ui.items.innerHTML='';(catalog[category]||[]).forEach(([v,i,n])=>{const b=document.createElement('button');b.className='item'+(v===selected?' on':'');b.innerHTML=`${i}<small>${n}</small>`;b.onclick=()=>{selected=v;if(category==='建材')selectedMat=v;drawItems()};ui.items.appendChild(b)})}syncShopCatalog();drawCats();drawItems();
const ray=new THREE.Raycaster(),camRay=new THREE.Raycaster();function aim(){ray.setFromCamera(new THREE.Vector2(0,0),camera);return ray.intersectObjects(buildAimTargets,true)[0]}function inWater(x,z){const rx=-38+z*.1,dx=(x-42)/1.35,dz=(z+38)/.78;return Math.abs(x-rx)<7||dx*dx+dz*dz<324}
function place(){if(playerState.mode!=='free')return;const h=aim();if(!h)return;const p=h.point;if(category==='形狀'||category==='建材'){const pos=h.object.userData.kind==='block'?h.object.position.clone().add(h.face.normal):p.clone();pos.y=h.object.userData.kind==='block'?Math.max(.5,Math.round(pos.y*2)/2):.5;const shape=category==='形狀'?selected:'cube',mat=category==='建材'?selected:selectedMat;if(!inWater(pos.x,pos.z))addBlock({x:Math.round(pos.x),y:pos.y,z:Math.round(pos.z),shape,mat,rot:objRot})}else if(!inWater(p.x,p.z))addObject({type:selected,x:Math.round(p.x),z:Math.round(p.z),rot:objRot,growth:.18})}
function remove(){if(playerState.mode!=='free')return toast('先離開家具再拆除');const h=aim();if(!h)return;let o=h.object;while(o.parent&&o.parent!==world)o=o.parent;if(o.userData.kind==='object'){unregisterSolid(o);unregisterCameraTarget(o);unregisterInteractionTarget(o);unregisterBuildAimTarget(o);unregisterWorldEntity(o);world.remove(o);objects.splice(objects.indexOf(o),1);const r=ranch.indexOf(o);if(r>=0)ranch.splice(r,1);const p=pets.indexOf(o);if(p>=0)pets.splice(p,1)}else if(h.object.userData.kind==='block'){unregisterSolid(h.object);unregisterCameraTarget(h.object);unregisterBuildAimTarget(h.object);unregisterWorldEntity(h.object);world.remove(h.object);blocks.delete(h.object.userData.id)}changed=true}

const JUMP_VELOCITY=.22,GRAVITY=.009,PLAYER_RADIUS=.30;
let yaw=-.4,pitch=-.16,moveX=0,moveY=0,vy=0,onGround=true;const playerState={mode:'free',anchor:null,previousCamera:null};
const collisionPoint=new THREE.Vector3(),collisionBox=new THREE.Box3();
function supportHeightAt(x,z){let top=0;const bucket=solidGrid.get(solidCellKey(Math.floor(x/SOLID_CELL),Math.floor(z/SOLID_CELL)));if(!bucket)return top;for(const g of bucket){if(g===playerState.anchor)continue;const box=collisionBox.setFromObject(g);if(x>=box.min.x-PLAYER_RADIUS&&x<=box.max.x+PLAYER_RADIUS&&z>=box.min.z-PLAYER_RADIUS&&z<=box.max.z+PLAYER_RADIUS)top=Math.max(top,box.max.y)}return top}
function solidAt(x,z){if(Math.abs(x)>HALF-2||Math.abs(z)>HALF-2||inWater(x,z))return true;collisionPoint.set(x,player.position.y+1,z);const bucket=solidGrid.get(solidCellKey(Math.floor(x/SOLID_CELL),Math.floor(z/SOLID_CELL)));if(!bucket)return false;for(const g of bucket){if(g===playerState.anchor)continue;if(collisionBox.setFromObject(g).expandByScalar(g.userData.collisionPad??(g.userData.kind==='block'?.24:.22)).containsPoint(collisionPoint))return true}return false}function movePlayer(dx,dz){if(playerState.mode!=='free')return;const nx=player.position.x+dx,nz=player.position.z+dz;if(!solidAt(nx,player.position.z))player.position.x=nx;if(!solidAt(player.position.x,nz))player.position.z=nz}
function enterFurniture(o,action){const a=furnitureAnchorWorld(o);if(!a)return;playerState.mode=action;playerState.anchor=o;playerState.previousCamera=cameraMode;if(cameraMode==='first'){cameraMode='third';ui.cam.textContent='🎥 第三人稱'}player.position.copy(a);player.rotation.y=furnitureYaw(o);vy=0;onGround=true;setCuteCharacterPose(player,action==='lie'?'lie':'sit');toast(action==='lie'?'躺下休息 🛏️':'坐下休息 ✓')}
function exitFurniture(){if(playerState.mode==='free')return;const o=playerState.anchor,e=o&&furnitureExitWorld(o);setCuteCharacterPose(player,'idle');if(e){player.position.set(e.x,0,e.z);player.rotation.y=furnitureYaw(o)}else player.position.y=0;playerState.mode='free';playerState.anchor=null;if(playerState.previousCamera){cameraMode=playerState.previousCamera;playerState.previousCamera=null;ui.cam.textContent=cameraLabel()}toast('起身 ✓')}

function snapshot(){return{version:4.3,savedAt:Date.now(),player:{x:player.position.x,y:0,z:player.position.z,yaw,pitch},blocks:[...blocks.values()].map(b=>({id:b.userData.id,x:b.position.x,y:b.position.y,z:b.position.z,shape:b.userData.shape,mat:b.userData.mat,rot:b.rotation.y})),objects:objects.map(o=>({id:o.userData.id,type:o.userData.type,x:o.position.x,z:o.position.z,rot:o.rotation.y,growth:o.userData.growth,affection:o.userData.affection,lastProductDay:o.userData.lastProductDay,productReady:o.userData.productReady}))}}
function saveWorld(){localStorage.setItem(SAVE_KEY,JSON.stringify(snapshot()));saveWorldIndex();changed=false}function loadWorld(){try{const d=JSON.parse(localStorage.getItem(SAVE_KEY)||localStorage.getItem(OLD_SAVE_KEY)||'null');if(!d)return false;(d.blocks||[]).forEach(addBlock);(d.objects||[]).forEach(r=>{if(r.type==='crop')r.type='carrot';if(r.type==='fruitTree')r.type='appleTree';addObject(r,false)});if(d.player){player.position.set(d.player.x||0,0,d.player.z||8);yaw=d.player.yaw??yaw;pitch=d.player.pitch??pitch;updateWorldEntity(player)}changed=false;return true}catch{return false}}const loaded=loadWorld();if(!loaded){addObject({type:'chair',x:1,z:10},false);addObject({type:'bed',x:4,z:10},false);addObject({type:'sofa',x:-3,z:10},false);addObject({type:'carrot',x:2,z:14,growth:1},false);addObject({type:'shippingBox',x:6,z:14},false);addObject({type:'petDog',x:-2,z:14},false)}saveWorldIndex();
function rebuildCrop(o){o.remove(o.userData.model);o.userData.model=createCropModel(o.userData.crop,o.userData.growth);o.add(o.userData.model)}function rebuildTree(o){o.remove(o.userData.model);o.userData.model=createFruitTreeModel(o.userData.treeKind,o.userData.growth,season);o.add(o.userData.model)}
function renderLife(){lifeUI.coins.textContent=`🪙 ${economy.coins}`;lifeUI.shipping.textContent=`📦 ${pendingShippingValue(economy)}`;const inv=Object.entries(economy.inventory).filter(([,q])=>q);lifeUI.inventory.innerHTML=inv.length?inv.map(([k,q])=>`<div class="invRow"><span>${ITEM_NAMES[k]||k}</span><b>×${q}</b></div>`).join(''):'目前沒有收成';lifeUI.shop.innerHTML=SHOP_ITEMS.map(x=>`<div class="shopRow"><span>${x.icon||'✨'} ${x.name}・🪙${x.price}</span><button class="buyBtn" data-buy="${x.id}" ${ownedCount(economy,x.id)?'disabled':''}>${ownedCount(economy,x.id)?'已擁有':'購買'}</button></div>`).join('')}lifeUI.btn.onclick=()=>{renderLife();lifeUI.panel.classList.add('open');lifeUI.close.classList.add('open')};lifeUI.close.onclick=()=>{lifeUI.panel.classList.remove('open');lifeUI.close.classList.remove('open')};lifeUI.shop.onclick=e=>{const b=e.target.closest('[data-buy]');if(!b)return;const shopId=b.dataset.buy,r=buyShopItem(economy,shopId);if(r.ok){syncShopCatalog();category='收藏';selected=SHOP_BUILD_UNLOCKS[shopId][0];drawCats();drawItems()}toast(r.ok?`買到 ${r.item.name}，已加入收藏建造`:`還差 ${r.need||0} 金幣`);renderLife();saveSettings()};
function nearestTarget(){if(playerState.mode!=='free')return{action:'leave',o:playerState.anchor};let best=null,dist=2.5;for(const o of interactionTargetsNear(player.position.x,player.position.z,dist)){const d=Math.hypot(o.position.x-player.position.x,o.position.z-player.position.z);if(d>=dist)continue;let action=null;if(isFurnitureInteractable(o.userData.type))action=getFurnitureInteraction(o.userData.type).action;else if(o.userData.crop&&o.userData.growth>=.95)action='harvest';else if(o.userData.treeKind&&o.userData.growth>=.95)action='fruit';else if(o.userData.shippingBox)action='shipping';else if(o.userData.ranch&&o.userData.productReady)action='product';else if(o.userData.pet)action='pet';if(action){best={action,o};dist=d}}return best}
function interactionLabel(t){if(!t)return['✨','互動'];if(t.action==='leave')return['🚶','起身'];if(t.action==='sit')return[getFurnitureInteraction(t.o.userData.type).icon,getFurnitureInteraction(t.o.userData.type).label];if(t.action==='lie')return['🛏️','躺下'];if(t.action==='harvest')return['🧺','收成'];if(t.action==='fruit')return['🍎','採果'];if(t.action==='shipping')return['📦','出貨'];if(t.action==='product')return['🥚','收取'];return['💗','摸摸']}
function interact(){const t=nearestTarget();if(!t)return toast('附近沒有可以互動的東西');const o=t.o;if(t.action==='leave')exitFurniture();else if(t.action==='sit'||t.action==='lie')enterFurniture(o,t.action);else if(t.action==='harvest'){addInventory(economy,o.userData.crop,1);o.userData.growth=.15;rebuildCrop(o);toast(`收成 ${ITEM_NAMES[o.userData.crop]}`)}else if(t.action==='fruit'){addInventory(economy,o.userData.treeKind,1);o.userData.growth=.72;rebuildTree(o);toast(`採到 ${ITEM_NAMES[o.userData.treeKind]}`)}else if(t.action==='shipping'){const r=shipAllSellable(economy);toast(r.count?`放進出貨箱 ${r.count} 件`:'沒有可出貨的東西')}else if(t.action==='product'){const k=o.userData.type==='cow'?'milk':o.userData.type==='sheep'?'wool':'egg';addInventory(economy,k,1);o.userData.productReady=false;o.userData.lastProductDay=worldDay;toast(`收取 ${ITEM_NAMES[k]}`)}else if(t.action==='pet'){o.userData.affection=Math.min(100,(o.userData.affection||0)+1);toast('摸摸 💗')}changed=true;renderLife();saveSettings()}lifeUI.interact.onclick=interact;

function cameraLabel(){return cameraMode==='first'?'👁 第一人稱':cameraMode==='third'?'🎥 第三人稱':'🌾 牧場視角'}function saveSettings(){localStorage.setItem(SETTINGS_KEY,JSON.stringify({...settings,cameraMode,farmDistance,farmPitch,farmYaw,season,weather,timeSpeed,simMinutes,worldDay,economy,avatar:player.userData.avatarStyle,avatarCustomization}))}ui.cam.textContent=cameraLabel();ui.cam.onclick=()=>{if(playerState.mode!=='free')return toast('先起身再切換視角');cameraMode=cameraMode==='first'?'third':cameraMode==='third'?'farm':'first';ui.cam.textContent=cameraLabel();if(cameraMode==='farm')toast('牧場視角：上下／左右拖曳調角度，雙指捏合調遠近');saveSettings()};ui.add.onclick=place;ui.del.onclick=remove;ui.rot.onclick=()=>objRot=(objRot+Math.PI/2)%(Math.PI*2);ui.jump.onclick=()=>{if(playerState.mode!=='free')return exitFurniture();if(onGround){vy=JUMP_VELOCITY;onGround=false}};ui.admin.onclick=()=>{ui.panel.classList.add('open');ui.closeAdmin.classList.add('open')};ui.closeAdmin.onclick=()=>{ui.panel.classList.remove('open');ui.closeAdmin.classList.remove('open')};ui.save.onclick=()=>{saveWorld();toast('世界已存檔 ✓')};function replaceAvatarCustomization(patch){if(playerState.mode!=='free')exitFurniture();avatarCustomization=normalizeAvatarCustomization({...avatarCustomization,...patch},patch.gender||avatarCustomization.gender);const p=player.position.clone(),r=player.rotation.y;world.remove(player);player=createAvatar(avatarCustomization.gender,avatarCustomization);player.userData.entityId='player-local';player.position.copy(p);player.rotation.y=r;world.add(player);registerWorldEntity(player,'player');saveSettings()}const avatarFields={gender:ui.avatar,age:ui.avatarAge,body:ui.avatarBody,skin:ui.avatarSkin,hairStyle:ui.avatarHairStyle,hair:ui.avatarHair,outfit:ui.avatarOutfit,top:ui.avatarTop,bottom:ui.avatarBottom,hat:ui.avatarHat,glasses:ui.avatarGlasses,accessory:ui.avatarAccessory};Object.entries(avatarFields).forEach(([key,control])=>control&&(control.onchange=e=>replaceAvatarCustomization({[key]:e.target.value})));ui.season.onchange=e=>{season=e.target.value;groundMat.color.setHex({spring:0x8fd47b,summer:0x70c36b,autumn:0xb8bd62,winter:0xdce8e5}[season]);objects.filter(o=>o.userData.treeKind).forEach(rebuildTree);saveSettings()};ui.weather.onchange=e=>{weather=e.target.value;saveSettings()};ui.timeSpeed.onchange=e=>{timeSpeed=Number(e.target.value);saveSettings()};$('#resetPos').onclick=()=>{if(playerState.mode!=='free')exitFurniture();player.position.set(0,0,8)};$('#backup').onclick=()=>navigator.clipboard?.writeText(JSON.stringify(snapshot()));
ui.season.value=season;ui.weather.value=weather;ui.timeSpeed.value=String(timeSpeed);ui.avatar.value=avatarCustomization.gender;ui.avatarAge.value=avatarCustomization.age;ui.avatarBody.value=avatarCustomization.body;ui.avatarSkin.value=avatarCustomization.skin;ui.avatarHairStyle.value=avatarCustomization.hairStyle;ui.avatarHair.value=avatarCustomization.hair;ui.avatarOutfit.value=avatarCustomization.outfit;ui.avatarTop.value=avatarCustomization.top;ui.avatarBottom.value=avatarCustomization.bottom;ui.avatarHat.value=avatarCustomization.hat;ui.avatarGlasses.value=avatarCustomization.glasses;ui.avatarAccessory.value=avatarCustomization.accessory;
let joyId=null;const joyRadius=()=>Math.max(1,(ui.joy.clientWidth-ui.knob.offsetWidth)/2);function setJoy(e){const r=ui.joy.getBoundingClientRect(),radius=joyRadius();let x=e.clientX-(r.left+r.width/2),y=e.clientY-(r.top+r.height/2),d=Math.hypot(x,y)||1,s=Math.min(radius,d)/d;x*=s;y*=s;ui.knob.style.transform=`translate(${x}px,${y}px)`;moveX=x/radius;moveY=y/radius}ui.joy.onpointerdown=e=>{joyId=e.pointerId;ui.joy.setPointerCapture(e.pointerId);setJoy(e)};ui.joy.onpointermove=e=>e.pointerId===joyId&&setJoy(e);ui.joy.onpointerup=ui.joy.onpointercancel=e=>{if(e.pointerId===joyId){joyId=null;moveX=moveY=0;ui.knob.style.transform=''}};
let lookId=null,lx=0,ly=0;const farmTouches=new Map();function farmTouchDistance(){const a=[...farmTouches.values()];return a.length<2?0:Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y)}function finishFarmPointer(e){farmTouches.delete(e.pointerId);if(farmTouches.size===1){const [id,p]=farmTouches.entries().next().value;lookId=id;lx=p.x;ly=p.y}else if(!farmTouches.size)lookId=null;saveSettings()}renderer.domElement.style.touchAction='none';renderer.domElement.onpointerdown=e=>{if(playerState.mode!=='free'||e.clientX<=innerWidth*.29)return;if(cameraMode==='farm'){renderer.domElement.setPointerCapture?.(e.pointerId);farmTouches.set(e.pointerId,{x:e.clientX,y:e.clientY});if(farmTouches.size===1){lookId=e.pointerId;lx=e.clientX;ly=e.clientY}else if(farmTouches.size===2){lookId=null}return}lookId=e.pointerId;lx=e.clientX;ly=e.clientY};renderer.domElement.onpointermove=e=>{if(cameraMode==='farm'){const p=farmTouches.get(e.pointerId);if(!p)return;if(farmTouches.size>=2){const before=farmTouchDistance();p.x=e.clientX;p.y=e.clientY;const after=farmTouchDistance();if(before>0&&after>0)farmDistance=Math.max(FARM_DISTANCE_MIN,Math.min(15.5,farmDistance*before/after))}else{farmYaw-=(e.clientX-lx)*.006;farmPitch=Math.max(.42,Math.min(1.12,farmPitch+(e.clientY-ly)*.006));lx=e.clientX;ly=e.clientY;p.x=e.clientX;p.y=e.clientY}return}if(e.pointerId!==lookId)return;yaw-=(e.clientX-lx)*.0075;pitch=Math.max(-1.08,Math.min(.6,pitch-(e.clientY-ly)*.006));lx=e.clientX;ly=e.clientY};renderer.domElement.onpointerup=finishFarmPointer;renderer.domElement.onpointercancel=finishFarmPointer;renderer.domElement.onwheel=e=>{if(cameraMode!=='farm')return;e.preventDefault();farmDistance=Math.max(FARM_DISTANCE_MIN,Math.min(15.5,farmDistance+e.deltaY*.01));saveSettings()};
function toast(m){ui.status.textContent=m;clearTimeout(toast.t);toast.t=setTimeout(()=>ui.status.textContent=`第 ${worldDay} 天・🪙 ${economy.coins}・${playerState.mode==='free'?'自由活動':playerState.mode==='sit'?'休息中':'躺下休息中'}`,1800)}function resize(){const w=visualViewport?.width||innerWidth,h=visualViewport?.height||innerHeight;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false)}addEventListener('resize',resize);visualViewport?.addEventListener('resize',resize);addEventListener('beforeunload',()=>{if(playerState.mode!=='free')exitFurniture();saveWorld();saveSettings()});setInterval(()=>changed&&saveWorld(),15000);
function readCropCare(){try{return JSON.parse(localStorage.getItem(CARE_KEY)||'{}')}catch{return{}}}
function growDay(){const fromDay=worldDay;worldDay++;const earned=settleShipping(economy),careStore=readCropCare();if(earned)toast(`出貨收入 +${earned} 金幣`);objects.forEach(o=>{const result=advanceDailyRecord(o.userData,{fromDay,toDay:worldDay,season,weather,care:careStore[o.userData.id]||null});if(result.growthChanged){if(o.userData.crop)rebuildCrop(o);else if(o.userData.treeKind)rebuildTree(o)}if(result.changed)changed=true});renderLife();saveWorld();saveSettings()}
const cameraDelta=new THREE.Vector3(),cameraHitPos=new THREE.Vector3(),moveForward=new THREE.Vector3(),moveRight=new THREE.Vector3(),eye=new THREE.Vector3(),desiredCamera=new THREE.Vector3(),farmFrom=new THREE.Vector3(),lookTarget=new THREE.Vector3();
function safeCamera(from,desired){cameraDelta.copy(desired).sub(from);const len=cameraDelta.length();if(len<.1)return desired;cameraDelta.normalize();camRay.set(from,cameraDelta);camRay.far=len;const h=camRay.intersectObjects(cameraTargets,false)[0];return h&&h.distance<len?cameraHitPos.copy(from).addScaledVector(cameraDelta,Math.max(.7,h.distance-.3)):desired}
globalThis.__AGCB_WORLD_HOTPATH={schema:7,cameraTargets,pets,solidGrid,solidCells,interactionGrid,interactionCells,buildAimTargets,buildAimTargetSet,wetGroundGroup,worldIndex,collisionPoint,collisionBox,reindexSolid,get cameraTargetCount(){return cameraTargets.length},get petCount(){return pets.length},get solidCellCount(){return solidGrid.size},get interactionCellCount(){return interactionGrid.size},get buildAimTargetCount(){return buildAimTargets.length},get worldChunkCount(){return Object.keys(worldIndex.chunks).length},get worldEntityCount(){return Object.keys(worldIndex.entities).length},get worldPartitionCount(){return WORLD_PARTITIONS.length}};
function turnHeading(current,target,amount){return current+Math.atan2(Math.sin(target-current),Math.cos(target-current))*amount}
let last=performance.now(),hintAt=0;function loop(t){requestAnimationFrame(loop);const dt=Math.min(2.2,(t-last)/16.67);last=t;const moving=Math.abs(moveX)+Math.abs(moveY)>.04;if(playerState.mode!=='free'&&moving)exitFurniture();const cy=cameraMode==='farm'?farmYaw:yaw;moveForward.set(-Math.sin(cy),0,-Math.cos(cy));moveRight.set(Math.cos(cy),0,-Math.sin(cy));const speed=.135*dt,dx=moveForward.x*(-moveY)*speed+moveRight.x*moveX*speed,dz=moveForward.z*(-moveY)*speed+moveRight.z*moveX*speed;movePlayer(dx,dz);updateWorldEntity(player);if(playerState.mode==='free'){const previousY=player.position.y,wasFalling=vy<=0;vy-=GRAVITY*dt;const nextY=previousY+vy*dt,supportY=supportHeightAt(player.position.x,player.position.z);if(wasFalling&&previousY>=supportY-.02&&nextY<=supportY){player.position.y=supportY;vy=0;onGround=true}else if(nextY<=0){player.position.y=0;vy=0;onGround=true}else{player.position.y=nextY;onGround=false}if(cameraMode==='first')player.rotation.y=yaw;else if(moving)player.rotation.y=turnHeading(player.rotation.y,Math.atan2(-dx,-dz),.24);animateCuteCharacter(player,t,moving,1.15)}
pets.forEach(g=>{const dx=player.position.x-g.position.x,dz=player.position.z-g.position.z,d=Math.hypot(dx,dz),m=playerState.mode==='free'&&d>2.7&&d<25;if(m){g.rotation.y=turnHeading(g.rotation.y,Math.atan2(-dx,-dz),.14);g.position.x+=dx/d*.018*dt;g.position.z+=dz/d*.018*dt;updateInteractionTarget(g);updateWorldEntity(g)}animateCuteCharacter(g.userData.model,t,m,1.1)});ranch.forEach(g=>{g.userData.phase+=.004*dt;const tx=g.userData.home.x+Math.sin(g.userData.phase)*3,tz=g.userData.home.y+Math.cos(g.userData.phase*.83)*3,dx=tx-g.position.x,dz=tz-g.position.z,d=Math.hypot(dx,dz);if(d>.12){g.rotation.y=turnHeading(g.rotation.y,Math.atan2(-dx,-dz),.1);g.position.x+=dx/d*.006*dt;g.position.z+=dz/d*.006*dt;updateInteractionTarget(g);updateWorldEntity(g)}animateAnimal(g.userData.model,t,d>.12?.006:0)});
const prev=simMinutes;simMinutes=(simMinutes+dt*.018*timeSpeed)%1440;if(simMinutes<prev)growDay();const hour=simMinutes/60,ang=(hour-6)/24*Math.PI*2,day=Math.max(0,Math.sin(ang));sun.intensity=.15+day*2.05;moon.intensity=(1-day)*.28;ui.clock.textContent=`${String(Math.floor(hour)).padStart(2,'0')}:${String(Math.floor(simMinutes%60)).padStart(2,'0')}`;
eye.set(player.position.x,player.position.y+(playerState.mode==='lie'?.65:1.62),player.position.z);if(cameraMode==='third'){desiredCamera.set(eye.x+Math.sin(yaw)*THIRD_CAMERA_DISTANCE,eye.y+1.85,eye.z+Math.cos(yaw)*THIRD_CAMERA_DISTANCE);camera.position.lerp(safeCamera(eye,desiredCamera),.3);camera.lookAt(eye)}else if(cameraMode==='farm'){const farmHorizontal=Math.cos(farmPitch)*farmDistance;desiredCamera.set(player.position.x+Math.sin(farmYaw)*farmHorizontal,player.position.y+.8+Math.sin(farmPitch)*farmDistance,player.position.z+Math.cos(farmYaw)*farmHorizontal);farmFrom.set(player.position.x,player.position.y+1,player.position.z);camera.position.lerp(safeCamera(farmFrom,desiredCamera),.2);lookTarget.set(player.position.x,player.position.y+.8,player.position.z);camera.lookAt(lookTarget)}else{camera.position.copy(eye);camera.rotation.order='YXZ';camera.rotation.y=yaw;camera.rotation.x=pitch}player.visible=cameraMode!=='first';if(t-hintAt>180){hintAt=t;const [i,l]=interactionLabel(nearestTarget());lifeUI.interact.innerHTML=`${i}<small>${l}</small>`}refreshWetGround();renderer.render(scene,camera)}
resize();renderLife();toast(loaded?'V0.4.55 已接續原世界':'V0.4.55 已建立世界');requestAnimationFrame(loop);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
