import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
import {createCuteChildAvatar,createCuteDog,createCuteCat,animateCuteCharacter} from './character-models.js';
import {createCow,createSheep,createChicken,animateAnimal} from './animal-models.js';
import {createCropModel,createFruitTreeModel} from './crop-models.js';
import {createEconomyState} from './economy-system.js';

const VERSION='V0.4',WORLD_SIZE=180,HALF=WORLD_SIZE/2;
const SAVE_KEY='ag_cute_blocks_world_v04',OLD_SAVE_KEY='ag_cute_blocks_world_v03',SETTINGS_KEY='ag_cute_blocks_settings_v03';
const ui={status:document.querySelector('#status'),cats:document.querySelector('#cats'),items:document.querySelector('#items'),cam:document.querySelector('#cam'),admin:document.querySelector('#admin'),panel:document.querySelector('#adminPanel'),season:document.querySelector('#season'),weather:document.querySelector('#weather'),timeSpeed:document.querySelector('#timeSpeed'),avatar:document.querySelector('#avatar'),save:document.querySelector('#saveNow'),closeAdmin:document.querySelector('#closeAdmin'),add:document.querySelector('#add'),del:document.querySelector('#del'),jump:document.querySelector('#jump'),rot:document.querySelector('#rot'),joy:document.querySelector('#joy'),knob:document.querySelector('#knob'),clock:document.querySelector('#clock')};
const scene=new THREE.Scene();scene.background=new THREE.Color(0x9ed9ff);scene.fog=new THREE.Fog(0x9ed9ff,62,170);
const camera=new THREE.PerspectiveCamera(68,innerWidth/innerHeight,.1,260);const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;document.body.prepend(renderer.domElement);
const hemi=new THREE.HemisphereLight(0xfff5d8,0x6e9864,2.15);scene.add(hemi);const sun=new THREE.DirectionalLight(0xffffff,2);sun.position.set(45,70,25);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);scene.add(sun);const moon=new THREE.DirectionalLight(0xb8c8ff,0);scene.add(moon);
const lm=c=>new THREE.MeshLambertMaterial({color:c});const mats={grass:lm(0x8fd47b),wood:lm(0xc99b68),darkwood:lm(0x805a43),stone:lm(0xaab0b6),marble:lm(0xe9e7e2),brick:lm(0xc97868),concrete:lm(0xc7cbce),white:lm(0xf7f4ed),pink:lm(0xf4a6b8),blue:lm(0x90c8ee),yellow:lm(0xf3d477),roof:lm(0xb86f58),soil:lm(0x79563b),metal:new THREE.MeshPhongMaterial({color:0x9da4aa,shininess:80}),glass:new THREE.MeshPhongMaterial({color:0xa8e8f3,transparent:true,opacity:.48,shininess:90,side:THREE.DoubleSide}),water:new THREE.MeshPhongMaterial({color:0x4fb7df,transparent:true,opacity:.73,shininess:100})};
const world=new THREE.Group();scene.add(world);const groundMat=mats.grass.clone();const ground=new THREE.Mesh(new THREE.PlaneGeometry(WORLD_SIZE,WORLD_SIZE),groundMat);ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;ground.userData.ground=true;world.add(ground);const grid=new THREE.GridHelper(WORLD_SIZE,WORLD_SIZE,0x679b5f,0x7abb70);grid.position.y=.008;grid.material.opacity=.13;grid.material.transparent=true;world.add(grid);
const waterMeshes=[];{const river=new THREE.Mesh(new THREE.PlaneGeometry(14,145),mats.water);river.rotation.x=-Math.PI/2;river.rotation.z=.1;river.position.set(-38,.035,3);world.add(river);waterMeshes.push(river);const lake=new THREE.Mesh(new THREE.CircleGeometry(18,48),mats.water);lake.rotation.x=-Math.PI/2;lake.position.set(42,.04,-38);lake.scale.set(1.35,.78,1);world.add(lake);waterMeshes.push(lake)}
const plotCenters=[[-58,-30],[-58,28],[-4,-54],[-2,53],[52,-8],[55,48]];for(const [i,p] of plotCenters.entries()){const pad=new THREE.Mesh(new THREE.PlaneGeometry(34,30),lm(i%2?0x96d483:0x9cda89));pad.material.transparent=true;pad.material.opacity=.38;pad.rotation.x=-Math.PI/2;pad.position.set(p[0],.012,p[1]);world.add(pad)}
const blocks=new Map(),objects=[],ranch=[],history=[],redoStack=[];let changed=false;
function id(){return globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`}
function box(parent,sx,sy,sz,x,y,z,mat='white'){const m=new THREE.Mesh(new THREE.BoxGeometry(sx,sy,sz),typeof mat==='number'?lm(mat):(mats[mat]||mats.white));m.position.set(x,y,z);m.castShadow=m.receiveShadow=true;parent.add(m);return m}
function sphere(parent,r,x,y,z,c,s=[1,1,1]){const m=new THREE.Mesh(new THREE.SphereGeometry(r,16,12),typeof c==='number'?lm(c):(mats[c]||mats.white));m.position.set(x,y,z);m.scale.set(...s);m.castShadow=true;parent.add(m);return m}
function geometryFor(shape){if(shape==='rect')return new THREE.BoxGeometry(2,1,1);if(shape==='cylinder')return new THREE.CylinderGeometry(.5,.5,1,20);if(shape==='sphere')return new THREE.SphereGeometry(.58,20,14);if(shape==='triangle'){const s=new THREE.Shape();s.moveTo(-.55,-.5);s.lineTo(.55,-.5);s.lineTo(0,.5);s.closePath();const g=new THREE.ExtrudeGeometry(s,{depth:1,bevelEnabled:false});g.translate(0,0,-.5);g.rotateY(Math.PI/2);return g}if(shape==='slope'){const s=new THREE.Shape();s.moveTo(-.5,-.5);s.lineTo(.5,-.5);s.lineTo(.5,.5);s.closePath();const g=new THREE.ExtrudeGeometry(s,{depth:1,bevelEnabled:false});g.translate(0,0,-.5);g.rotateY(Math.PI/2);return g}if(shape==='roof'){const s=new THREE.Shape();s.moveTo(-.65,-.4);s.lineTo(0,.4);s.lineTo(.65,-.4);s.closePath();const g=new THREE.ExtrudeGeometry(s,{depth:1.4,bevelEnabled:false});g.translate(0,0,-.7);g.rotateY(Math.PI/2);return g}return new THREE.BoxGeometry(1,1,1)}
function addBlock(rec,mark=true){const k=rec.id||id(),m=new THREE.Mesh(geometryFor(rec.shape||'cube'),mats[rec.mat]||mats.wood);m.position.set(rec.x,rec.y,rec.z);m.rotation.y=rec.rot||0;m.castShadow=m.receiveShadow=true;m.userData={kind:'block',id:k,shape:rec.shape||'cube',mat:rec.mat||'wood'};world.add(m);blocks.set(k,m);if(mark){history.push({op:'addBlock',id:k});redoStack.length=0;changed=true}return m}
function makeDoor(g){box(g,1.05,2.05,.16,0,1.03,0,'darkwood');sphere(g,.06,.35,1.02,-.1,0xe3c65f)}
function makeWindow(g){box(g,1.5,.12,.12,0,1.35,0,'white');box(g,.12,1.25,.12,-.69,.75,0,'white');box(g,.12,1.25,.12,.69,.75,0,'white');const pane=new THREE.Mesh(new THREE.PlaneGeometry(1.25,1.05),mats.glass);pane.position.set(0,.8,.02);g.add(pane)}
function makeShippingBox(g){box(g,1.55,1.05,1.05,0,.52,0,'wood');const lid=box(g,1.65,.16,1.15,0,1.12,0,'darkwood');lid.rotation.x=-.12;box(g,.9,.36,.05,0,.65,-.54,0xffefd1)}
function addObject(rec,mark=true){const g=new THREE.Group();g.position.set(rec.x||0,0,rec.z||0);g.rotation.y=rec.rot||0;g.userData={kind:'object',id:rec.id||id(),type:rec.type,solid:true,growth:rec.growth??.2};const t=rec.type;
if(t==='chair'){box(g,.8,.12,.8,0,.65,0,'wood');for(const X of[-.3,.3])for(const Z of[-.3,.3])box(g,.12,.7,.12,X,.3,Z,'wood');box(g,.8,.78,.12,0,1,-.34,'wood')}
else if(t==='table'){box(g,1.8,.14,1.2,0,1,0,'wood');for(const X of[-.72,.72])for(const Z of[-.42,.42])box(g,.12,1,.12,X,.5,Z,'wood')}
else if(t==='sofa'){box(g,2.2,.55,.9,0,.42,0,0xe98ca0);box(g,2.2,.9,.25,0,.92,.32,0xe98ca0);box(g,.28,.65,.9,-1.08,.55,0,0xe98ca0);box(g,.28,.65,.9,1.08,.55,0,0xe98ca0)}
else if(t==='bed'){box(g,2.2,.45,1.45,0,.35,0,'darkwood');box(g,2.05,.3,1.3,0,.65,0,0xfff0d8);box(g,.75,.18,1.1,-.58,.83,0,'white')}
else if(t==='cabinet'){box(g,1.6,1.45,.5,0,.72,0,'wood');for(const X of[-.42,.42])box(g,.06,.32,.06,X,.78,-.27,'metal')}
else if(t==='fridge'){box(g,.95,1.9,.85,0,.95,0,0xf2f5f6);box(g,.04,.7,.05,.28,1.35,-.44,'metal')}
else if(t==='washer'){box(g,1,1.05,.85,0,.52,0,'white');const d=new THREE.Mesh(new THREE.CylinderGeometry(.28,.28,.04,24),mats.metal);d.rotation.x=Math.PI/2;d.position.set(0,.48,-.45);g.add(d)}
else if(t==='tv'){box(g,1.7,1,.12,0,1.15,0,0x242a31);box(g,.15,.65,.15,0,.45,.1,'metal');box(g,1,.08,.55,0,.1,.1,'metal')}
else if(t==='stove'){box(g,1.05,.95,.8,0,.48,0,0x55575b);for(const X of[-.25,.25])for(const Z of[-.18,.18]){const p=new THREE.Mesh(new THREE.CylinderGeometry(.11,.11,.02,16),lm(0x202226));p.position.set(X,.97,Z);g.add(p)}}
else if(t==='lamp'){box(g,.12,1.35,.12,0,.7,0,'metal');sphere(g,.32,0,1.5,0,0xffefa8);g.userData.solid=false}
else if(t==='door')makeDoor(g);else if(t==='window')makeWindow(g);else if(t==='shippingBox'){makeShippingBox(g);g.userData.shippingBox=true}
else if(t==='petDog'||t==='petCat'){const pet=t==='petDog'?createCuteDog():createCuteCat();g.add(pet);g.userData.solid=false;g.userData.pet=true;g.userData.model=pet}
else if(['cow','sheep','chicken'].includes(t)){const a=t==='cow'?createCow():t==='sheep'?createSheep():createChicken();g.add(a);g.userData.solid=false;g.userData.ranch=true;g.userData.model=a;g.userData.home=new THREE.Vector2(g.position.x,g.position.z);g.userData.phase=Math.random()*6.28;ranch.push(g)}
else if(['carrot','corn','pumpkin','tomato','strawberry','cabbage','potato'].includes(t)){const crop=createCropModel(t,g.userData.growth);g.add(crop);g.userData.solid=false;g.userData.crop=t;g.userData.model=crop;g.userData.lastGrowthDay=rec.lastGrowthDay??worldDay}
else if(['appleTree','orangeTree','peachTree'].includes(t)){const kind=t.replace('Tree','');const tree=createFruitTreeModel(kind,rec.growth??1,season);g.add(tree);g.userData.treeKind=kind;g.userData.model=tree;g.userData.solid=true}
else if(t==='tree'){box(g,.42,2,.42,0,1,0,'wood');sphere(g,1.18,0,2.15,0,0x67ad62,[1,.9,1])}
else if(t==='fence'){box(g,2,.12,.12,0,.6,0,'wood');box(g,2,.12,.12,0,1.08,0,'wood');box(g,.14,1.35,.14,-.9,.65,0,'wood');box(g,.14,1.35,.14,.9,.65,0,'wood')}
else return null;world.add(g);objects.push(g);if(mark){history.push({op:'addObject',id:g.userData.id});redoStack.length=0;changed=true}return g}
let settings={};try{settings=JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}')}catch{}let season=settings.season||'spring',weather=settings.weather||'sunny',timeSpeed=Number(settings.timeSpeed||1),simMinutes=settings.simMinutes??480,worldDay=Number(settings.worldDay||1),economy=createEconomyState(settings.economy||{});
function createAvatar(style){return createCuteChildAvatar(style)}let player=createAvatar(settings.avatar||'girl');world.add(player);player.position.set(0,0,8);
const catalog={'形狀':[['cube','▣','正方體'],['rect','▬','長方體'],['sphere','●','圓形'],['cylinder','⬤','圓柱'],['triangle','▲','三角形'],['slope','◢','斜坡'],['roof','⌂','屋頂塊']],'建材':[['wood','🪵','木材'],['darkwood','🟫','深木'],['stone','🪨','石材'],['marble','◻️','大理石'],['brick','🧱','磚'],['concrete','⬜','混凝土'],['glass','🪟','玻璃'],['roof','🏠','屋瓦'],['pink','🌸','粉色']],'建築':[['door','🚪','門'],['window','🪟','窗'],['fence','🪵','圍欄']],'家具':[['chair','🪑','椅子'],['table','🍽️','桌子'],['sofa','🛋️','沙發'],['bed','🛏️','床'],['lamp','💡','燈']],'家電':[['fridge','🧊','冰箱'],['stove','🍳','爐具'],['washer','🧺','洗衣機'],['tv','📺','電視'],['cabinet','🗄️','櫃子']],'農作':[['carrot','🥕','紅蘿蔔'],['corn','🌽','玉米'],['pumpkin','🎃','南瓜'],['tomato','🍅','番茄'],['strawberry','🍓','草莓'],['cabbage','🥬','高麗菜'],['potato','🥔','馬鈴薯']],'果樹':[['appleTree','🍎','蘋果樹'],['orangeTree','🍊','橘子樹'],['peachTree','🍑','桃樹'],['tree','🌳','樹木']],'動物':[['petDog','🐶','小狗'],['petCat','🐱','小貓'],['chicken','🐔','雞'],['cow','🐄','牛'],['sheep','🐑','羊']],'生活':[['shippingBox','📦','出貨箱']]};
let category='形狀',selectedShape='cube',selectedMat='wood',selectedObject='door',objRot=0,third=!!settings.third;
function drawCats(){ui.cats.innerHTML='';for(const k of Object.keys(catalog)){const b=document.createElement('button');b.className='cat'+(k===category?' on':'');b.textContent=k;b.onclick=()=>{category=k;if(k==='形狀')selectedShape=catalog[k][0][0];else if(k==='建材')selectedMat=catalog[k][0][0];else selectedObject=catalog[k][0][0];drawCats();drawItems()};ui.cats.appendChild(b)}}
function drawItems(){ui.items.innerHTML='';for(const [idv,ico,name] of catalog[category]){const active=category==='形狀'?idv===selectedShape:category==='建材'?idv===selectedMat:idv===selectedObject,b=document.createElement('button');b.className='item'+(active?' on':'');b.innerHTML=`${ico}<small>${name}</small>`;b.onclick=()=>{if(category==='形狀')selectedShape=idv;else if(category==='建材')selectedMat=idv;else selectedObject=idv;drawItems()};ui.items.appendChild(b)}}drawCats();drawItems();
const ray=new THREE.Raycaster();function allTargets(){const a=[ground,...waterMeshes,...blocks.values()];for(const g of objects)g.traverse(o=>{if(o.isMesh)a.push(o)});return a}function aim(){ray.setFromCamera(new THREE.Vector2(0,0),camera);return ray.intersectObjects(allTargets(),false)[0]}function inWater(x,z){const riverX=-38+z*.1,dx=(x-42)/1.35,dz=(z+38)/.78;return Math.abs(x-riverX)<7||dx*dx+dz*dz<324}const snap=v=>Math.round(v);
function place(){const h=aim();if(!h)return;const p=h.point.clone();if(category==='形狀'||category==='建材'){let pos=h.object.userData?.kind==='block'?h.object.position.clone().add(h.face.normal):p;pos.y=h.object.userData?.kind==='block'?Math.max(.5,Math.round(pos.y*2)/2):.5;if(inWater(pos.x,pos.z))return toast('水面上目前不能建造');addBlock({x:snap(pos.x),y:pos.y,z:snap(pos.z),shape:category==='形狀'?selectedShape:'cube',mat:selectedMat,rot:objRot})}else{if(inWater(p.x,p.z))return toast('水面上目前不能放置');addObject({type:selectedObject,x:snap(p.x),z:snap(p.z),rot:objRot,growth:.18})}}
function remove(){const h=aim();if(!h||h.object===ground||waterMeshes.includes(h.object))return;let o=h.object;while(o.parent&&o.parent!==world)o=o.parent;if(o.userData.kind==='object'){world.remove(o);const i=objects.indexOf(o);if(i>=0)objects.splice(i,1);const r=ranch.indexOf(o);if(r>=0)ranch.splice(r,1);changed=true}else if(h.object.userData.kind==='block'){world.remove(h.object);blocks.delete(h.object.userData.id);changed=true}}
let yaw=-.4,pitch=-.16,moveX=0,moveY=0,vy=0,onGround=true;function solidAt(x,z,y=1){if(Math.abs(x)>HALF-2||Math.abs(z)>HALF-2||inWater(x,z))return true;const p=new THREE.Vector3(x,Math.max(.35,y),z);for(const b of blocks.values())if(new THREE.Box3().setFromObject(b).expandByScalar(.24).containsPoint(p))return true;for(const g of objects)if(g.userData.solid&&new THREE.Box3().setFromObject(g).expandByScalar(.22).containsPoint(p))return true;return false}function movePlayer(dx,dz){const nx=player.position.x+dx,nz=player.position.z+dz;if(!solidAt(nx,player.position.z,player.position.y+1))player.position.x=nx;if(!solidAt(player.position.x,nz,player.position.y+1))player.position.z=nz}
function snapshot(){return {version:4,savedAt:Date.now(),player:{x:player.position.x,y:player.position.y,z:player.position.z,yaw,pitch},blocks:[...blocks.values()].map(b=>({id:b.userData.id,x:b.position.x,y:b.position.y,z:b.position.z,shape:b.userData.shape,mat:b.userData.mat,rot:b.rotation.y})),objects:objects.map(o=>({id:o.userData.id,type:o.userData.type,x:o.position.x,z:o.position.z,rot:o.rotation.y,growth:o.userData.growth,lastGrowthDay:o.userData.lastGrowthDay}))}}
function saveWorld(silent=false){try{localStorage.setItem(SAVE_KEY,JSON.stringify(snapshot()));changed=false;if(!silent)toast('世界已存檔 ✓')}catch{if(!silent)toast('存檔空間不足')}}function loadWorld(){try{const raw=localStorage.getItem(SAVE_KEY)||localStorage.getItem(OLD_SAVE_KEY);if(!raw)return false;const d=JSON.parse(raw);for(const r of d.blocks||[])addBlock(r,false);for(const r of d.objects||[]){if(r.type==='crop')r.type='carrot';if(r.type==='fruitTree')r.type='appleTree';addObject(r,false)}if(d.player){player.position.set(d.player.x||0,d.player.y||0,d.player.z||8);yaw=d.player.yaw??yaw;pitch=d.player.pitch??pitch}changed=false;return true}catch(e){console.warn(e);return false}}const loaded=loadWorld();
if(!loaded){addObject({id:'starter-apple',type:'appleTree',x:-48,z:-22,growth:1},false);addObject({id:'starter-dog',type:'petDog',x:2,z:10},false);addObject({id:'starter-box',type:'shippingBox',x:-55,z:-22},false)}
const particles=new THREE.Group();scene.add(particles);function rebuildWeather(){while(particles.children.length)particles.remove(particles.children[0]);scene.fog=new THREE.Fog(scene.background,weather==='fog'?22:62,weather==='fog'?95:170);if(weather==='rain'||weather==='snow'){const count=weather==='rain'?260:190,geo=new THREE.BufferGeometry(),arr=new Float32Array(count*3);for(let i=0;i<count;i++){arr[i*3]=(Math.random()-.5)*70;arr[i*3+1]=Math.random()*35;arr[i*3+2]=(Math.random()-.5)*70}geo.setAttribute('position',new THREE.BufferAttribute(arr,3));particles.add(new THREE.Points(geo,new THREE.PointsMaterial({color:weather==='rain'?0xa8d8ff:0xffffff,size:weather==='rain'?.09:.18,transparent:true,opacity:.75})))}}
function refreshSeasonModels(){groundMat.color.setHex({spring:0x8fd47b,summer:0x70c36b,autumn:0xb8bd62,winter:0xdce8e5}[season]);for(const o of objects)if(o.userData.treeKind){o.remove(o.userData.model);o.userData.model=createFruitTreeModel(o.userData.treeKind,o.userData.growth??1,season);o.add(o.userData.model)}ui.season.value=season}function applyWeather(){ui.weather.value=weather;rebuildWeather()}refreshSeasonModels();applyWeather();
function saveSettings(){settings={...settings,avatar:player.userData.avatarStyle||'girl',third,season,weather,timeSpeed,simMinutes,worldDay,economy};localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings))}function setAvatar(style){const p=player.position.clone();world.remove(player);player=createAvatar(style);player.position.copy(p);world.add(player);ui.avatar.value=style;saveSettings()}ui.avatar.value=settings.avatar||'girl';ui.timeSpeed.value=String(timeSpeed);ui.cam.textContent=third?'🎥 第三人稱':'👁 第一人稱';
ui.add.onclick=place;ui.del.onclick=remove;ui.rot.onclick=()=>{objRot=(objRot+Math.PI/2)%(Math.PI*2);toast('已旋轉 90°')};ui.jump.onclick=()=>{if(onGround){vy=.15;onGround=false}};ui.cam.onclick=()=>{third=!third;ui.cam.textContent=third?'🎥 第三人稱':'👁 第一人稱';saveSettings()};ui.admin.onclick=()=>ui.panel.classList.add('open');ui.closeAdmin.onclick=()=>ui.panel.classList.remove('open');ui.save.onclick=()=>saveWorld(false);ui.season.onchange=e=>{season=e.target.value;refreshSeasonModels();saveSettings()};ui.weather.onchange=e=>{weather=e.target.value;applyWeather();saveSettings()};ui.timeSpeed.onchange=e=>{timeSpeed=Number(e.target.value);saveSettings()};ui.avatar.onchange=e=>setAvatar(e.target.value);document.querySelector('#resetPos').onclick=()=>{player.position.set(0,0,8);yaw=-.4;pitch=-.16;toast('已回到中央出生點')};document.querySelector('#backup').onclick=()=>navigator.clipboard?.writeText(JSON.stringify(snapshot())).then(()=>toast('世界備份已複製')).catch(()=>toast('此瀏覽器無法複製備份'));
const joy=ui.joy,knob=ui.knob;let joyId=null;function setJoy(e){const r=joy.getBoundingClientRect();let x=e.clientX-(r.left+r.width/2),y=e.clientY-(r.top+r.height/2),d=Math.hypot(x,y)||1,s=Math.min(39,d)/d;x*=s;y*=s;knob.style.transform=`translate(${x}px,${y}px)`;moveX=x/39;moveY=y/39}joy.addEventListener('pointerdown',e=>{joyId=e.pointerId;joy.setPointerCapture(e.pointerId);setJoy(e)});joy.addEventListener('pointermove',e=>{if(e.pointerId===joyId)setJoy(e)});function joyEnd(e){if(e.pointerId===joyId){joyId=null;moveX=moveY=0;knob.style.transform=''}}joy.addEventListener('pointerup',joyEnd);joy.addEventListener('pointercancel',joyEnd);let lookId=null,lx=0,ly=0;renderer.domElement.addEventListener('pointerdown',e=>{if(e.clientX>innerWidth*.29){lookId=e.pointerId;lx=e.clientX;ly=e.clientY;renderer.domElement.setPointerCapture(e.pointerId)}});renderer.domElement.addEventListener('pointermove',e=>{if(e.pointerId!==lookId)return;yaw-=(e.clientX-lx)*.0075;pitch-=(e.clientY-ly)*.0061;pitch=Math.max(-1.08,Math.min(.6,pitch));lx=e.clientX;ly=e.clientY});renderer.domElement.addEventListener('pointerup',e=>{if(e.pointerId===lookId)lookId=null});
const seasonNames={spring:'春',summer:'夏',autumn:'秋',winter:'冬'},weatherNames={sunny:'晴',cloudy:'陰',rain:'雨',fog:'霧',snow:'雪'};function toast(msg){ui.status.textContent=msg;clearTimeout(toast.t);toast.t=setTimeout(()=>ui.status.textContent=`${seasonNames[season]}・${weatherNames[weather]}・第 ${worldDay} 天・🪙 ${economy.coins}・自動存檔`,1800)}function resize(){const w=Math.max(1,Math.round(visualViewport?.width||innerWidth)),h=Math.max(1,Math.round(visualViewport?.height||innerHeight));camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false);renderer.domElement.style.width=w+'px';renderer.domElement.style.height=h+'px'}addEventListener('resize',resize);visualViewport?.addEventListener('resize',resize);document.addEventListener('gesturestart',e=>e.preventDefault(),{passive:false});document.addEventListener('contextmenu',e=>e.preventDefault());addEventListener('beforeunload',()=>{saveWorld(true);saveSettings()});document.addEventListener('visibilitychange',()=>{if(document.hidden){saveWorld(true);saveSettings()}});setInterval(()=>{if(changed)saveWorld(true)},15000);
function growDay(){worldDay++;for(const o of objects){if(o.userData.crop&&o.userData.growth<1){const seasonOk={carrot:['spring','autumn'],corn:['summer'],pumpkin:['autumn'],tomato:['spring','summer'],strawberry:['spring'],cabbage:['spring','winter'],potato:['spring','autumn']}[o.userData.crop]?.includes(season);if(seasonOk){const bonus=weather==='rain'?.23:.15;o.userData.growth=Math.min(1,o.userData.growth+bonus);o.remove(o.userData.model);o.userData.model=createCropModel(o.userData.crop,o.userData.growth);o.add(o.userData.model);changed=true}}}saveSettings()}
function updateLighting(dt){const prev=simMinutes;simMinutes=(simMinutes+dt*.018*timeSpeed)%1440;if(simMinutes<prev)growDay();const hour=simMinutes/60,ang=(hour-6)/24*Math.PI*2,daylight=Math.max(0,Math.sin(ang));sun.intensity=.15+daylight*2.05;moon.intensity=(1-daylight)*.28;sun.position.set(Math.cos(ang)*65,Math.max(8,Math.sin(ang)*70),25);const sky=daylight<.18?0x263858:weather==='cloudy'||weather==='rain'?0xa9bac5:season==='winter'?0xb9d6e6:0x9ed9ff;scene.background.setHex(sky);scene.fog.color.copy(scene.background);ui.clock.textContent=`${String(Math.floor(hour)).padStart(2,'0')}:${String(Math.floor(simMinutes%60)).padStart(2,'0')}`}
function updateWeather(dt){if(particles.children.length){const pts=particles.children[0],a=pts.geometry.attributes.position.array;for(let i=1;i<a.length;i+=3){a[i]-=(weather==='rain'?.32:.07)*dt;if(a[i]<0)a[i]=35}pts.geometry.attributes.position.needsUpdate=true;particles.position.x=player.position.x;particles.position.z=player.position.z}}
function updateCreatures(t,dt){for(const g of objects)if(g.userData.pet){const dx=player.position.x-g.position.x,dz=player.position.z-g.position.z,dist=Math.hypot(dx,dz),moving=dist>2.7&&dist<25;if(moving){g.rotation.y=Math.atan2(dx,dz);g.position.x+=dx/dist*.018*dt;g.position.z+=dz/dist*.018*dt}animateCuteCharacter(g.userData.model,t,moving,1.1)}for(const g of ranch){g.userData.phase+=.004*dt;const hx=g.userData.home.x,hz=g.userData.home.y,tx=hx+Math.sin(g.userData.phase)*3.2,tz=hz+Math.cos(g.userData.phase*.83)*3.2,dx=tx-g.position.x,dz=tz-g.position.z,dist=Math.hypot(dx,dz);if(dist>.12){g.rotation.y=Math.atan2(dx,dz);g.position.x+=dx/dist*.006*dt;g.position.z+=dz/dist*.006*dt}animateAnimal(g.userData.model,t,dist>.12?.006:0)}}
let last=performance.now();function loop(t){requestAnimationFrame(loop);const dt=Math.min(2.2,(t-last)/16.67);last=t;const f=new THREE.Vector3(-Math.sin(yaw),0,-Math.cos(yaw)),r=new THREE.Vector3(Math.cos(yaw),0,-Math.sin(yaw)),speed=.135*dt,moving=Math.abs(moveX)+Math.abs(moveY)>.04;movePlayer(f.x*(-moveY)*speed+r.x*moveX*speed,f.z*(-moveY)*speed+r.z*moveX*speed);vy-=.009*dt;player.position.y+=vy*dt;if(player.position.y<=0){player.position.y=0;vy=0;onGround=true}player.rotation.y=yaw+Math.PI;animateCuteCharacter(player,t,moving,1.15);const eye=player.position.clone().add(new THREE.Vector3(0,1.62,0));if(third){const back=new THREE.Vector3(Math.sin(yaw)*4.4,2.15,Math.cos(yaw)*4.4);camera.position.lerp(eye.clone().add(back),.28);camera.lookAt(eye.clone().add(f.clone().multiplyScalar(3)).add(new THREE.Vector3(0,pitch*2.4,0)));player.visible=true}else{camera.position.copy(eye);camera.rotation.order='YXZ';camera.rotation.y=yaw;camera.rotation.x=pitch;player.visible=false}updateLighting(dt);updateWeather(dt);updateCreatures(t,dt);renderer.render(scene,camera)}
resize();toast(loaded?'V0.4 已接續原世界存檔':'V0.4 已建立新的長期世界');requestAnimationFrame(loop);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
