[build]
  publish = "."
  command = "echo 'AG Cute Blocks TEST direct static deploy'"

[[headers]]
  for = "/*"
  [headers.values]
    X-AGCB-Environment = "TEST"
    Cache-Control = "no-cache"

[build.processing]
  skip_processing = true
