[build]
  publish = "dist-test"
  command = "bash ./netlify-build-test.sh"

[[headers]]
  for = "/*"
  [headers.values]
    X-AGCB-Environment = "TEST"
    Cache-Control = "no-cache"

[build.processing]
  skip_processing = true
