// AG Cute Blocks V0.5.241 deterministic TEST matrix for local-save fallback.
// Pure in-memory harness: never touches browser localStorage or PROD data.
const SAVE='ag_cute_blocks_world_v04',OLD='ag_cute_blocks_world_v03',BACKUP='ag_cute_blocks_world_v04_corrupt_backup';
const parse=raw=>{if(!raw)return null;try{const d=JSON.parse(raw);return d&&typeof d==='object'&&!Array.isArray(d)?d:null}catch{return null}};
const valid=d=>!!d&&(Array.isArray(d.blocks)||Array.isArray(d.objects)||!!d.player);
class Store{constructor(seed={},failKeys=[]){this.m=new Map(Object.entries(seed));this.failKeys=new Set(failKeys)}getItem(k){return this.m.has(k)?this.m.get(k):null}setItem(k,v){if(this.failKeys.has(k))throw new Error(`injected write failure: ${k}`);this.m.set(k,String(v))}}
function recover(store){let status='CURRENT_OK';try{const currentRaw=store.getItem(SAVE),current=parse(currentRaw);if(!valid(current)){const legacyRaw=store.getItem(OLD),legacy=parse(legacyRaw);if(valid(legacy)){if(currentRaw&&!store.getItem(BACKUP)){try{store.setItem(BACKUP,currentRaw)}catch{}}store.setItem(SAVE,legacyRaw);const verify=parse(store.getItem(SAVE));status=valid(verify)?(currentRaw?'RECOVERED_CORRUPT_CURRENT':'MIGRATED_LEGACY'):'RECOVERY_WRITE_FAILED'}else status=currentRaw?'CURRENT_INVALID_NO_LEGACY':'NO_SAVE'}}catch{status='PRELOAD_ERROR'}return status}
const goodCurrent=JSON.stringify({version:4.3,blocks:[],objects:[],player:{x:1},savedAt:100}),goodLegacy=JSON.stringify({blocks:[],player:{x:2}}),bad='{broken';
const cases=[
 ['current-valid',new Store({[SAVE]:goodCurrent,[OLD]:goodLegacy}),'CURRENT_OK',goodCurrent,null],
 ['current-corrupt-legacy-valid',new Store({[SAVE]:bad,[OLD]:goodLegacy}),'RECOVERED_CORRUPT_CURRENT',goodLegacy,bad],
 ['current-missing-legacy-valid',new Store({[OLD]:goodLegacy}),'MIGRATED_LEGACY',goodLegacy,null],
 ['both-invalid',new Store({[SAVE]:bad,[OLD]:'[]'}),'CURRENT_INVALID_NO_LEGACY',bad,null],
 ['migration-write-fails',new Store({[OLD]:goodLegacy},[SAVE]),'PRELOAD_ERROR',null,null]
];
let failed=0;for(const [name,store,wantStatus,wantSave,wantBackup] of cases){const got=recover(store),save=store.getItem(SAVE),backup=store.getItem(BACKUP);const ok=got===wantStatus&&save===wantSave&&backup===wantBackup;console.log(`${ok?'PASS':'FAIL'} ${name}: ${got}`);if(!ok){failed++;console.error({wantStatus,got,wantSave,save,wantBackup,backup})}}
const takeover=new Store({[OLD]:goodLegacy});const firstBoot=recover(takeover);takeover.setItem(SAVE,goodCurrent);const firstSaved=parse(takeover.getItem(SAVE));const secondBoot=recover(takeover);const takeoverOk=firstBoot==='MIGRATED_LEGACY'&&firstSaved?.version===4.3&&firstSaved?.savedAt===100&&secondBoot==='CURRENT_OK'&&takeover.getItem(OLD)===goodLegacy;console.log(`${takeoverOk?'PASS':'FAIL'} legacy-current-schema-takeover: ${firstBoot} -> v${firstSaved?.version} -> ${secondBoot}`);if(!takeoverOk)failed++;
const recovered=new Store({[SAVE]:bad,[OLD]:goodLegacy});const recoverBoot=recover(recovered);recovered.setItem(SAVE,goodCurrent);const recoverNext=recover(recovered);const recoveredOk=recoverBoot==='RECOVERED_CORRUPT_CURRENT'&&recoverNext==='CURRENT_OK'&&recovered.getItem(BACKUP)===bad;console.log(`${recoveredOk?'PASS':'FAIL'} recovered-current-schema-takeover: ${recoverBoot} -> ${recoverNext}`);if(!recoveredOk)failed++;
const bad2='{broken-again';const preserve=new Store({[SAVE]:bad,[OLD]:goodLegacy});const preserveFirst=recover(preserve);preserve.setItem(SAVE,bad2);const preserveSecond=recover(preserve);const preserveOk=preserveFirst==='RECOVERED_CORRUPT_CURRENT'&&preserveSecond==='RECOVERED_CORRUPT_CURRENT'&&preserve.getItem(BACKUP)===bad&&preserve.getItem(SAVE)===goodLegacy;console.log(`${preserveOk?'PASS':'FAIL'} first-corrupt-backup-preserved: ${preserveFirst} -> ${preserveSecond}`);if(!preserveOk)failed++;
// Backup failure is non-fatal: OLD remains authoritative recovery source and SAVE may still recover.
const backupFail=new Store({[SAVE]:bad,[OLD]:goodLegacy},[BACKUP]);const backupFailStatus=recover(backupFail);const backupFailOk=backupFailStatus==='RECOVERED_CORRUPT_CURRENT'&&backupFail.getItem(SAVE)===goodLegacy&&backupFail.getItem(OLD)===goodLegacy&&backupFail.getItem(BACKUP)===null;console.log(`${backupFailOk?'PASS':'FAIL'} backup-write-failure-nonfatal: ${backupFailStatus}`);if(!backupFailOk)failed++;
// If backup succeeds but SAVE migration fails, original corrupt SAVE, preserved BACKUP and OLD all remain.
// Removing the injected failure and retrying must recover without data loss.
const migrateFail=new Store({[SAVE]:bad,[OLD]:goodLegacy},[SAVE]);const migrateFailFirst=recover(migrateFail);const afterFailOk=migrateFailFirst==='PRELOAD_ERROR'&&migrateFail.getItem(SAVE)===bad&&migrateFail.getItem(BACKUP)===bad&&migrateFail.getItem(OLD)===goodLegacy;migrateFail.failKeys.delete(SAVE);const migrateRetry=recover(migrateFail);const migrateRetryOk=migrateRetry==='RECOVERED_CORRUPT_CURRENT'&&migrateFail.getItem(SAVE)===goodLegacy&&migrateFail.getItem(BACKUP)===bad;const migrationFailureOk=afterFailOk&&migrateRetryOk;console.log(`${migrationFailureOk?'PASS':'FAIL'} backup-kept-when-migration-fails-and-retry-recovers: ${migrateFailFirst} -> ${migrateRetry}`);if(!migrationFailureOk)failed++;
if(failed)throw new Error(`AGCB local-save matrix failed: ${failed}/10`);console.log('PASS matrix: 10/10');
