// AG Cute Blocks V0.5.242 deterministic TEST matrix for local-save fallback.
const SAVE='ag_cute_blocks_world_v04',OLD='ag_cute_blocks_world_v03',BACKUP='ag_cute_blocks_world_v04_corrupt_backup';
const parse=raw=>{if(!raw)return null;try{const d=JSON.parse(raw);return d&&typeof d==='object'&&!Array.isArray(d)?d:null}catch{return null}};
const finite=v=>Number.isFinite(Number(v));const sanePlayer=p=>!!p&&typeof p==='object'&&!Array.isArray(p)&&finite(p.x)&&finite(p.y)&&finite(p.z);const saneRecord=r=>!!r&&typeof r==='object'&&!Array.isArray(r)&&finite(r.x)&&finite(r.z)&&(r.y===undefined||finite(r.y));const valid=d=>!!d&&typeof d==='object'&&!Array.isArray(d)&&Array.isArray(d.blocks)&&Array.isArray(d.objects)&&sanePlayer(d.player)&&d.blocks.length<=20000&&d.objects.length<=10000&&d.blocks.every(saneRecord)&&d.objects.every(saneRecord);
class Store{constructor(seed={},failKeys=[]){this.m=new Map(Object.entries(seed));this.failKeys=new Set(failKeys)}getItem(k){return this.m.has(k)?this.m.get(k):null}setItem(k,v){if(this.failKeys.has(k))throw new Error(`injected write failure: ${k}`);this.m.set(k,String(v))}}
function recover(store){let status='CURRENT_OK';try{const currentRaw=store.getItem(SAVE),current=parse(currentRaw);if(!valid(current)){const legacyRaw=store.getItem(OLD),legacy=parse(legacyRaw);if(valid(legacy)){if(currentRaw&&!store.getItem(BACKUP)){try{store.setItem(BACKUP,currentRaw)}catch{}}store.setItem(SAVE,legacyRaw);const verify=parse(store.getItem(SAVE));status=valid(verify)?(currentRaw?'RECOVERED_CORRUPT_CURRENT':'MIGRATED_LEGACY'):'RECOVERY_WRITE_FAILED'}else status=currentRaw?'CURRENT_INVALID_NO_LEGACY':'NO_SAVE'}}catch{status='PRELOAD_ERROR'}return status}
const goodCurrent=JSON.stringify({version:4.3,blocks:[],objects:[],player:{x:1,y:2,z:3},savedAt:100}),goodLegacy=JSON.stringify({blocks:[],objects:[],player:{x:2,y:1,z:2}}),bad='{broken';let failed=0;
function gate(name,ok,detail=''){console.log(`${ok?'PASS':'FAIL'} ${name}${detail?`: ${detail}`:''}`);if(!ok)failed++}
for(const [name,store,wantStatus,wantSave,wantBackup] of [['current-valid',new Store({[SAVE]:goodCurrent,[OLD]:goodLegacy}),'CURRENT_OK',goodCurrent,null],['current-corrupt-legacy-valid',new Store({[SAVE]:bad,[OLD]:goodLegacy}),'RECOVERED_CORRUPT_CURRENT',goodLegacy,bad],['current-missing-legacy-valid',new Store({[OLD]:goodLegacy}),'MIGRATED_LEGACY',goodLegacy,null],['both-invalid',new Store({[SAVE]:bad,[OLD]:'[]'}),'CURRENT_INVALID_NO_LEGACY',bad,null],['migration-write-fails',new Store({[OLD]:goodLegacy},[SAVE]),'PRELOAD_ERROR',null,null]]){const got=recover(store);gate(name,got===wantStatus&&store.getItem(SAVE)===wantSave&&store.getItem(BACKUP)===wantBackup,got)}
const takeover=new Store({[OLD]:goodLegacy});const firstBoot=recover(takeover);takeover.setItem(SAVE,goodCurrent);const secondBoot=recover(takeover);gate('legacy-current-schema-takeover',firstBoot==='MIGRATED_LEGACY'&&secondBoot==='CURRENT_OK'&&takeover.getItem(OLD)===goodLegacy,`${firstBoot} -> ${secondBoot}`);
const recovered=new Store({[SAVE]:bad,[OLD]:goodLegacy});const recoverBoot=recover(recovered);recovered.setItem(SAVE,goodCurrent);const recoverNext=recover(recovered);gate('recovered-current-schema-takeover',recoverBoot==='RECOVERED_CORRUPT_CURRENT'&&recoverNext==='CURRENT_OK'&&recovered.getItem(BACKUP)===bad,`${recoverBoot} -> ${recoverNext}`);
const bad2='{broken-again';const preserve=new Store({[SAVE]:bad,[OLD]:goodLegacy});const preserveFirst=recover(preserve);preserve.setItem(SAVE,bad2);const preserveSecond=recover(preserve);gate('first-corrupt-backup-preserved',preserveFirst==='RECOVERED_CORRUPT_CURRENT'&&preserveSecond==='RECOVERED_CORRUPT_CURRENT'&&preserve.getItem(BACKUP)===bad&&preserve.getItem(SAVE)===goodLegacy,`${preserveFirst} -> ${preserveSecond}`);
const backupFail=new Store({[SAVE]:bad,[OLD]:goodLegacy},[BACKUP]);const backupFailStatus=recover(backupFail);gate('backup-write-failure-nonfatal',backupFailStatus==='RECOVERED_CORRUPT_CURRENT'&&backupFail.getItem(SAVE)===goodLegacy&&backupFail.getItem(OLD)===goodLegacy&&backupFail.getItem(BACKUP)===null,backupFailStatus);
const migrateFail=new Store({[SAVE]:bad,[OLD]:goodLegacy},[SAVE]);const migrateFailFirst=recover(migrateFail);const afterFail=migrateFailFirst==='PRELOAD_ERROR'&&migrateFail.getItem(SAVE)===bad&&migrateFail.getItem(BACKUP)===bad&&migrateFail.getItem(OLD)===goodLegacy;migrateFail.failKeys.delete(SAVE);const migrateRetry=recover(migrateFail);gate('backup-kept-when-migration-fails-and-retry-recovers',afterFail&&migrateRetry==='RECOVERED_CORRUPT_CURRENT'&&migrateFail.getItem(SAVE)===goodLegacy&&migrateFail.getItem(BACKUP)===bad,`${migrateFailFirst} -> ${migrateRetry}`);
for(const [name,legacy] of [['legacy-player-only',{player:{x:1,y:1,z:1}}],['legacy-wrong-array-types',{blocks:{},objects:[],player:{x:1,y:1,z:1}}],['legacy-invalid-player-coord',{blocks:[],objects:[],player:{x:'NaN',y:1,z:1}}],['legacy-invalid-record',{blocks:[{x:'oops',y:1,z:1}],objects:[],player:{x:1,y:1,z:1}}]]){const store=new Store({[SAVE]:bad,[OLD]:JSON.stringify(legacy)});const got=recover(store);gate(name,got==='CURRENT_INVALID_NO_LEGACY'&&store.getItem(SAVE)===bad&&store.getItem(BACKUP)===null,got)}
if(failed)throw new Error(`AGCB local-save matrix failed: ${failed}/14`);console.log('PASS matrix: 14/14');
