// AG Cute Blocks V0.5.243 deterministic TEST matrix for authentic V0.4 local-save fallback.
const SAVE='ag_cute_blocks_world_v04',OLD='ag_cute_blocks_world_v03',BACKUP='ag_cute_blocks_world_v04_corrupt_backup';
const parse=raw=>{if(!raw)return null;try{const d=JSON.parse(raw);return d&&typeof d==='object'&&!Array.isArray(d)?d:null}catch{return null}};
const finite=v=>Number.isFinite(Number(v));
const sanePlayer=(p,{legacy=false}={})=>!!p&&typeof p==='object'&&!Array.isArray(p)&&finite(p.x)&&finite(p.z)&&(legacy?(p.y===undefined||finite(p.y)):finite(p.y));
const saneBlock=r=>!!r&&typeof r==='object'&&!Array.isArray(r)&&finite(r.x)&&finite(r.y)&&finite(r.z);
const saneObject=r=>!!r&&typeof r==='object'&&!Array.isArray(r)&&finite(r.x)&&finite(r.z)&&typeof r.type==='string'&&r.type.length>0;
const collections=d=>Array.isArray(d.blocks)&&Array.isArray(d.objects)&&d.blocks.length<=20000&&d.objects.length<=10000&&d.blocks.every(saneBlock)&&d.objects.every(saneObject);
const validCurrent=d=>!!d&&typeof d==='object'&&!Array.isArray(d)&&collections(d)&&sanePlayer(d.player);
const validLegacy=d=>!!d&&typeof d==='object'&&!Array.isArray(d)&&collections(d)&&sanePlayer(d.player,{legacy:true});
class Store{constructor(seed={},failKeys=[]){this.m=new Map(Object.entries(seed));this.failKeys=new Set(failKeys)}getItem(k){return this.m.has(k)?this.m.get(k):null}setItem(k,v){if(this.failKeys.has(k))throw new Error(`injected write failure: ${k}`);this.m.set(k,String(v))}}
function recover(store){let status='CURRENT_OK';try{const currentRaw=store.getItem(SAVE),current=parse(currentRaw);if(!validCurrent(current)){const legacyRaw=store.getItem(OLD),legacy=parse(legacyRaw);if(validLegacy(legacy)){if(currentRaw&&!store.getItem(BACKUP)){try{store.setItem(BACKUP,currentRaw)}catch{}}store.setItem(SAVE,legacyRaw);const verify=parse(store.getItem(SAVE));status=validLegacy(verify)?(currentRaw?'RECOVERED_CORRUPT_CURRENT':'MIGRATED_LEGACY'):'RECOVERY_WRITE_FAILED'}else status=currentRaw?'CURRENT_INVALID_NO_LEGACY':'NO_SAVE'}}catch{status='PRELOAD_ERROR'}return status}
const current=JSON.stringify({version:4,blocks:[],objects:[],player:{x:1,y:2,z:3}}),legacyBase={blocks:[{x:1,y:.5,z:2}],objects:[{type:'tree',x:3,z:4}],player:{x:2,z:2}},legacy=JSON.stringify(legacyBase),bad='{broken';let failed=0;
function gate(name,ok,detail=''){console.log(`${ok?'PASS':'FAIL'} ${name}${detail?`: ${detail}`:''}`);if(!ok)failed++}
for(const [name,seed,want] of [['current-valid',{[SAVE]:current,[OLD]:legacy},'CURRENT_OK'],['legacy-no-id-no-object-y',{[OLD]:legacy},'MIGRATED_LEGACY'],['legacy-crop',{[OLD]:JSON.stringify({...legacyBase,objects:[{type:'crop',x:3,z:4}]})},'MIGRATED_LEGACY'],['legacy-fruitTree',{[OLD]:JSON.stringify({...legacyBase,objects:[{type:'fruitTree',x:3,z:4}]})},'MIGRATED_LEGACY'],['corrupt-current-valid-legacy',{[SAVE]:bad,[OLD]:legacy},'RECOVERED_CORRUPT_CURRENT'],['invalid-empty-type',{[OLD]:JSON.stringify({...legacyBase,objects:[{type:'',x:3,z:4}]})},'NO_SAVE'],['invalid-block-y',{[OLD]:JSON.stringify({...legacyBase,blocks:[{x:1,y:'NaN',z:2}]})},'NO_SAVE'],['invalid-object-z',{[OLD]:JSON.stringify({...legacyBase,objects:[{type:'tree',x:3,z:'bad'}]})},'NO_SAVE'],['invalid-legacy-player-x',{[OLD]:JSON.stringify({...legacyBase,player:{x:'bad',z:2}})},'NO_SAVE'],['invalid-legacy-player-y-when-present',{[OLD]:JSON.stringify({...legacyBase,player:{x:2,y:'bad',z:2}})},'NO_SAVE']]){const r=new Store(seed),got=recover(r);gate(name,got===want,got)}
const recovered=new Store({[SAVE]:bad,[OLD]:legacy});const rs=recover(recovered);gate('first-corrupt-backup-preserved',rs==='RECOVERED_CORRUPT_CURRENT'&&recovered.getItem(BACKUP)===bad,rs);
const writeFail=new Store({[OLD]:legacy},[SAVE]);gate('migration-write-failure-is-preload-error',recover(writeFail)==='PRELOAD_ERROR');
if(failed)throw new Error(`AGCB V0.5.243 matrix failed: ${failed}/12`);console.log('PASS matrix: 12/12 authentic V0.4 compatibility locks');
