// AG Cute Blocks wardrobe runtime — V0.5.23
import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
const VERSION='V0.5.23',KEY='agcb.wardrobe.v3';
const COLORS={'黑色':0x252229,'白色':0xf8f6f1,'藍色':0x78aee8,'灰色':0x9298a2,'紅色':0xd95762,'黃色':0xf1cf5b,'粉紅色':0xf1a4b5};
let state={earsOn:true,earsColor:'黑色',outfitColor:'粉紅色',bowType:'關閉',bowColor:'粉紅色',wingType:'關閉',wingColor:'粉紅色'};try{state={...state,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{}
const generatedRootName='agcb-wardrobe-generated-root';
function candidates(){const out=[];const add=x=>{if(x?.traverse&&!out.includes(x))out.push(x)};[window.playerModel,window.characterModel,window.player?.model,window.AGOriginalCharacter?.current,window.AGOriginalCharacter?.model].forEach(add);if(window.scene?.traverse)window.scene.traverse(o=>{if(/character|player|avatar|ag-original/i.test(o.name||''))add(o)});return out}
function finalRoot(){const a=candidates();return a.length?a[a.length-1]:null}
function material(c,a=1){return new THREE.MeshStandardMaterial({color:c,roughness:.62,metalness:.03,transparent:a<1,opacity:a,side:THREE.DoubleSide})}
function removeGenerated(root){const kill=[];root.traverse(o=>{if(o.name===generatedRootName)kill.push(o)});kill.forEach(o=>o.parent?.remove(o))}
function recolorNamed(root,re,color){root.traverse(o=>{if(!re.test(o.name||'')||!o.material)return;const ms=Array.isArray(o.material)?o.material:[o.material];ms.forEach(m=>m?.color?.setHex(color))})}
function setNamedVisible(root,re,on){root.traverse(o=>{if(re.test(o.name||''))o.visible=on})}
function bow(g,type,c){const x=new THREE.Group(),big=type==='特大蝴蝶結',m=material(c);x.name='wardrobe-bow';for(const s of[-1,1]){const l=new THREE.Mesh(new THREE.SphereGeometry(1,14,10),m);l.scale.set(big?.36:.28,big?.27:.21,.09);l.position.set(s*(big?.26:.20),0,0);l.rotation.z=s*.28;x.add(l)}x.add(new THREE.Mesh(new THREE.SphereGeometry(big?.14:.11,14,10),m));x.position.set(0,.84,.24);g.add(x)}
function wing(g,x,y,sx,sy,r,c,a=.86){const w=new THREE.Mesh(new THREE.SphereGeometry(1,14,10),material(c,a));w.scale.set(sx,sy,.055);w.position.set(x,y,0);w.rotation.z=r;g.add(w)}
function wings(g,type,c){const x=new THREE.Group();x.name='wardrobe-wings';x.position.set(0,1.18,.22);const angel=type.includes('天使'),demon=type.includes('惡魔'),huge=type.includes('大天使');for(const s of[-1,1]){if(demon){wing(x,s*.30,.04,.36,.15,s*.50,c);wing(x,s*.49,.13,.25,.10,s*.72,c)}else if(angel){wing(x,s*(huge?.40:.31),.08,huge?.50:.37,huge?.20:.15,s*(huge?.43:.35),c,.9);wing(x,s*(huge?.50:.39),-.13,huge?.42:.31,huge?.16:.12,s*(huge?.63:.52),c,.9)}else{wing(x,s*.30,.14,.31,.24,s*.36,c,.72);wing(x,s*.28,-.14,.25,.19,-s*.30,c,.72)}}g.add(x)}
function applyTo(root){removeGenerated(root);setNamedVisible(root,/cat.?ear|neko|貓耳/i,state.earsOn);if(state.earsOn)recolorNamed(root,/cat.?ear|neko|貓耳/i,COLORS[state.earsColor]);recolorNamed(root,/dress|outfit|cloth|clothes|top|bottom|skirt|shirt|hoodie/i,COLORS[state.outfitColor]);const g=new THREE.Group();g.name=generatedRootName;if(state.bowType!=='關閉')bow(g,state.bowType,COLORS[state.bowColor]);if(state.wingType!=='關閉')wings(g,state.wingType,COLORS[state.wingColor]);root.add(g);root.userData.agWardrobeVersion=VERSION}
let last=null,timer=0;function apply(){localStorage.setItem(KEY,JSON.stringify(state));const root=finalRoot();if(!root){clearTimeout(timer);timer=setTimeout(apply,350);return}if(last&&last!==root)removeGenerated(last);last=root;applyTo(root);window.dispatchEvent(new CustomEvent('ag-wardrobe-applied',{detail:{...state,version:VERSION}}))}
function watchFinalCharacter(){let stable=0,prev=null;const tick=()=>{const r=finalRoot();if(r&&r===prev)stable++;else stable=0;prev=r;if(r&&stable===3&&r!==last)apply();setTimeout(tick,400)};tick()}
function mount(){if(document.getElementById('agWardrobeBtn'))return;const style=document.createElement('style');style.textContent=`#agWardrobeBtn{position:fixed;z-index:88;right:max(18px,env(safe-area-inset-right));top:max(118px,calc(env(safe-area-inset-top) + 108px));border:3px solid #fff;border-radius:18px;background:#fffde8e8;padding:8px 11px;font-weight:900;color:#42565c;box-shadow:0 3px 12px #0002}#agWardrobe{display:none;position:fixed;z-index:150;inset:0;background:#0005;align-items:center;justify-content:center;padding:16px}#agWardrobe.open{display:flex}#agWardrobeCard{width:min(580px,94vw);max-height:86dvh;overflow:auto;background:#fffaf0;border-radius:22px;padding:16px;color:#3d5556}.agWSec{border-top:1px solid #eadfce;padding:11px 0}.agWTitle{font-weight:900;margin-bottom:7px}.agWOptions{display:flex;gap:7px;flex-wrap:wrap}.agWOpt{border:2px solid #e5dccb;border-radius:12px;background:#fff;padding:8px 10px;font-weight:800}.agWOpt.on{outline:3px solid #ffe06b}.agWClose{float:right;border:0;border-radius:50%;width:38px;height:38px;background:#fff;font-size:22px;font-weight:900}`;document.head.appendChild(style);const btn=document.createElement('button');btn.id='agWardrobeBtn';btn.textContent='👗 衣櫃';document.body.appendChild(btn);const modal=document.createElement('div');modal.id='agWardrobe';modal.innerHTML=`<div id="agWardrobeCard"><button class="agWClose">×</button><h2>👗 衣櫃 <small>${VERSION}</small></h2><div id="agWBody"></div></div>`;document.body.appendChild(modal);const body=modal.querySelector('#agWBody');const colorKeys=Object.keys(COLORS);const sections=[['貓耳 開關','earsOn',[['關閉',false],['開啟',true]]],['貓耳顏色','earsColor',colorKeys.map(x=>[x,x])],['服裝顏色','outfitColor',colorKeys.map(x=>[x,x])],['腰部蝴蝶結','bowType',[['關閉','關閉'],['和服大蝴蝶結','和服大蝴蝶結'],['特大蝴蝶結','特大蝴蝶結']]],['蝴蝶結顏色','bowColor',colorKeys.map(x=>[x,x])],['背部翅膀','wingType',[['關閉','關閉'],['蝴蝶翅膀','蝴蝶翅膀'],['天使翅膀','天使翅膀'],['大天使翅膀','大天使翅膀'],['惡魔翅膀','惡魔翅膀']]],['翅膀顏色','wingColor',colorKeys.map(x=>[x,x])]];function render(){body.innerHTML='';for(const [title,k,opts] of sections){const sec=document.createElement('div');sec.className='agWSec';sec.innerHTML=`<div class="agWTitle">${title}</div><div class="agWOptions"></div>`;const box=sec.lastElementChild;for(const [label,val] of opts){const b=document.createElement('button');b.className='agWOpt'+(state[k]===val?' on':'');b.textContent=label;b.onclick=()=>{state[k]=val;render();apply()};box.appendChild(b)}body.appendChild(sec)}}btn.onclick=()=>{render();modal.classList.add('open')};modal.querySelector('.agWClose').onclick=()=>modal.classList.remove('open');modal.onclick=e=>{if(e.target===modal)modal.classList.remove('open')};render();watchFinalCharacter();setTimeout(apply,1200)}
window.AGWardrobe={version:VERSION,get:()=>({...state}),set:v=>{state={...state,...v};apply()}};document.readyState==='loading'?document.addEventListener('DOMContentLoaded',mount):mount();
