// AG Cute Blocks wardrobe runtime — V0.5.21
import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
const VERSION='V0.5.21',KEY='agcb.wardrobe.v2';
const COLORS={'原色':null,'白色':0xf8f6f1,'藍色':0x78aee8,'灰色':0x9298a2,'紅色':0xd95762,'黃色':0xf1cf5b,'粉紅色':0xf1a4b5};
const BACKS=['關閉','和服大蝴蝶結','特大蝴蝶結','蝴蝶翅膀','天使翅膀','大天使翅膀','惡魔翅膀'];
let state={color:'原色',ears:'開啟',bow:'關閉',wings:'關閉'};try{state={...state,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{}
const mats=new Map();
function roots(){const a=[];for(const x of [window.playerModel,window.characterModel,window.player?.model,window.AGOriginalCharacter?.current,window.AGOriginalCharacter?.model])if(x?.traverse&&!a.includes(x))a.push(x);if(window.scene?.traverse)window.scene.traverse(o=>{if((o.name||'').match(/agcb|character|player/i)&&o.traverse&&!a.includes(o))a.push(o)});return a}
function remember(o){if(!o.material)return;const list=Array.isArray(o.material)?o.material:[o.material];for(const m of list)if(m?.color&&!mats.has(m))mats.set(m,m.color.getHex())}
function restore(){for(const [m,c] of mats)if(m?.color)m.color.setHex(c)}
function isEar(o){return /ear|neko|cat.?ear|貓耳/i.test(o.name||'')||o.userData?.agWardrobeSlot==='ears'}
function setEars(root,on){root.traverse(o=>{if(isEar(o)){if(o.userData.agWardrobeBaseVisible===undefined)o.userData.agWardrobeBaseVisible=o.visible;o.visible=on?o.userData.agWardrobeBaseVisible:false}})}
function recolor(root){root.traverse(o=>{remember(o);if(state.color==='原色'||!o.material)return;const n=(o.name||'').toLowerCase();if(/eye|skin|hair|face|mouth/.test(n))return;const list=Array.isArray(o.material)?o.material:[o.material];for(const m of list)if(m?.color)m.color.setHex(COLORS[state.color])})}
const mat=(c,a=1)=>new THREE.MeshStandardMaterial({color:c,roughness:.62,metalness:.03,transparent:a<1,opacity:a,side:THREE.DoubleSide});
function clearGenerated(root){const kill=[];root.traverse(o=>{if(o.userData?.agWardrobeGenerated)kill.push(o)});kill.forEach(o=>o.parent?.remove(o))}
function bow(root,type,c){const g=new THREE.Group();g.userData.agWardrobeGenerated=true;g.name='agcb-wardrobe-bow';const big=type==='特大蝴蝶結',m=mat(c);for(const s of[-1,1]){const l=new THREE.Mesh(new THREE.SphereGeometry(1,14,10),m);l.scale.set(big?.36:.28,big?.27:.21,.09);l.position.set(s*(big?.26:.20),0,0);l.rotation.z=s*.28;g.add(l)}const k=new THREE.Mesh(new THREE.SphereGeometry(big?.14:.11,14,10),m);g.add(k);g.position.set(0,.84,.24);root.add(g)}
function wingMesh(g,x,y,sx,sy,r,c,a){const w=new THREE.Mesh(new THREE.SphereGeometry(1,14,10),mat(c,a));w.scale.set(sx,sy,.055);w.position.set(x,y,0);w.rotation.z=r;g.add(w)}
function wings(root,type,c){const g=new THREE.Group();g.userData.agWardrobeGenerated=true;g.name='agcb-wardrobe-wings';g.position.set(0,1.18,.22);const angel=type.includes('天使'),demon=type.includes('惡魔'),huge=type.includes('大天使');for(const s of[-1,1]){if(demon){wingMesh(g,s*.30,.04,.36,.15,s*.50,c,.9);wingMesh(g,s*.49,.13,.25,.10,s*.72,c,.9)}else if(angel){const wc=huge?0xfffdf5:c;wingMesh(g,s*(huge?.40:.31),.08,huge?.50:.37,huge?.20:.15,s*(huge?.43:.35),wc,.88);wingMesh(g,s*(huge?.50:.39),-.13,huge?.42:.31,huge?.16:.12,s*(huge?.63:.52),wc,.88)}else{wingMesh(g,s*.30,.14,.31,.24,s*.36,c,.72);wingMesh(g,s*.28,-.14,.25,.19,-s*.30,c,.72)}}root.add(g)}
function apply(){localStorage.setItem(KEY,JSON.stringify(state));const rs=roots();if(!rs.length){setTimeout(apply,500);return}restore();for(const root of rs){clearGenerated(root);setEars(root,state.ears==='開啟');recolor(root);const c=COLORS[state.color]??0xf1a4b5;if(state.bow!=='關閉')bow(root,state.bow,c);if(state.wings!=='關閉')wings(root,state.wings,c)}window.dispatchEvent(new CustomEvent('ag-wardrobe-applied',{detail:{...state}}))}
function mount(){if(document.getElementById('agWardrobeBtn'))return;const css=document.createElement('style');css.textContent=`#agWardrobeBtn{position:fixed;z-index:88;right:max(18px,env(safe-area-inset-right));top:max(118px,calc(env(safe-area-inset-top) + 108px));border:3px solid #fff;border-radius:18px;background:#fffde8e8;padding:8px 11px;font-weight:900;color:#42565c;box-shadow:0 3px 12px #0002}#agWardrobe{display:none;position:fixed;z-index:150;inset:0;background:#0005;align-items:center;justify-content:center;padding:16px}#agWardrobe.open{display:flex}#agWardrobeCard{width:min(560px,92vw);max-height:86dvh;overflow:auto;background:#fffaf0;border-radius:22px;padding:16px;color:#3d5556}.agWSection{border-top:1px solid #eadfce;padding:12px 0}.agWTitle{font-size:17px;font-weight:900;margin-bottom:7px}.agWOptions{display:flex;gap:7px;flex-wrap:wrap}.agWOpt{border:2px solid #e5dccb;border-radius:12px;background:#fff;padding:8px 10px;font-weight:800}.agWOpt.on{outline:3px solid #ffe06b}.agWClose{float:right;border:0;border-radius:50%;width:38px;height:38px;background:#fff;font-size:22px;font-weight:900}`;document.head.appendChild(css);const btn=document.createElement('button');btn.id='agWardrobeBtn';btn.textContent='👗 衣櫃';document.body.appendChild(btn);const modal=document.createElement('div');modal.id='agWardrobe';modal.innerHTML=`<div id="agWardrobeCard"><button class="agWClose">×</button><h2>👗 衣櫃 <small>${VERSION}</small></h2><div class="agWSection"><div class="agWTitle">服裝色系</div><div class="agWOptions" data-k="color"></div></div><div class="agWSection"><div class="agWTitle">貓耳</div><div class="agWOptions" data-k="ears"></div></div><div class="agWSection"><div class="agWTitle">腰部蝴蝶結</div><div class="agWOptions" data-k="bow"></div></div><div class="agWSection"><div class="agWTitle">背部翅膀</div><div class="agWOptions" data-k="wings"></div></div></div>`;document.body.appendChild(modal);const sets={color:Object.keys(COLORS),ears:['關閉','開啟'],bow:['關閉','和服大蝴蝶結','特大蝴蝶結'],wings:['關閉','蝴蝶翅膀','天使翅膀','大天使翅膀','惡魔翅膀']};const render=()=>Object.entries(sets).forEach(([k,arr])=>{const box=modal.querySelector(`[data-k="${k}"]`);box.innerHTML='';for(const v of arr){const b=document.createElement('button');b.className='agWOpt'+(state[k]===v?' on':'');b.textContent=v;b.onclick=()=>{state[k]=v;render();apply()};box.appendChild(b)}});btn.onclick=()=>{render();modal.classList.add('open')};modal.querySelector('.agWClose').onclick=()=>modal.classList.remove('open');modal.onclick=e=>{if(e.target===modal)modal.classList.remove('open')};render();apply()}
window.AGWardrobe={version:VERSION,get:()=>({...state}),set:v=>{state={...state,...v};apply()}};document.readyState==='loading'?document.addEventListener('DOMContentLoaded',mount):mount();
