// AG Cute Blocks wardrobe runtime — V0.5.19
// Live wardrobe: recolours compatible character materials and mounts lightweight 3D back accessories.
import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
const VERSION='V0.5.19',KEY='agcb.wardrobe.v1';
const COLORS={'白色':0xf8f6f1,'藍色':0x78aee8,'灰色':0x9298a2,'紅色':0xd95762,'黃色':0xf1cf5b,'粉紅色':0xf1a4b5};
const BACKS=['無','和服大蝴蝶結','特大蝴蝶結','蝴蝶翅膀','天使翅膀','大天使翅膀','惡魔翅膀'];
let state={color:'粉紅色',back:'無',ears:'貓耳'};try{state={...state,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{}
const mat=(c,transparent=false)=>new THREE.MeshStandardMaterial({color:c,roughness:.62,metalness:.03,transparent,opacity:transparent?.82:1,side:THREE.DoubleSide});
function findCharacter(){return window.playerModel||window.characterModel||window.player?.model||document.querySelector('canvas')?.__agCharacter||null}
function wing(parent,x,y,z,sx,sy,rot,c){const m=new THREE.Mesh(new THREE.SphereGeometry(1,14,10),mat(c,true));m.scale.set(sx,sy,.055);m.position.set(x,y,z);m.rotation.z=rot;m.name='agcb-wardrobe-wing';parent.add(m)}
function bow(parent,c,big=false){const g=new THREE.Group();g.name='agcb-wardrobe-back';const m=mat(c);for(const s of[-1,1]){const l=new THREE.Mesh(new THREE.SphereGeometry(1,14,10),m);l.scale.set(big?.34:.27,big?.25:.20,.09);l.position.set(s*(big?.25:.20),0,0);l.rotation.z=s*.28;g.add(l)}const knot=new THREE.Mesh(new THREE.SphereGeometry(big?.13:.11,14,10),m);g.add(knot);for(const s of[-1,1]){const t=new THREE.Mesh(new THREE.CapsuleGeometry(big?.075:.06,big?.34:.27,6,10),m);t.position.set(s*.10,-(big?.30:.24),.01);t.rotation.z=s*.22;g.add(t)}g.position.set(0,.86,.24);parent.add(g)}
function wings(parent,type,c){const g=new THREE.Group();g.name='agcb-wardrobe-back';g.position.set(0,1.18,.22);const angel=type.includes('天使'),demon=type.includes('惡魔'),huge=type.includes('大天使');if(demon){for(const s of[-1,1]){wing(g,s*.28,.03,0,.34,.15,s*.48,c);wing(g,s*.48,.12,0,.25,.10,s*.72,c)}}else if(angel){const wc=type==='大天使翅膀'?0xfffdf5:c;for(const s of[-1,1]){wing(g,s*(huge?.38:.30),.08,0,huge?.48:.36,huge?.19:.15,s*(huge?.42:.35),wc);wing(g,s*(huge?.48:.38),-.12,0,huge?.40:.30,huge?.15:.12,s*(huge?.62:.52),wc)}}else{for(const s of[-1,1]){wing(g,s*.30,.13,0,.30,.23,s*.36,c);wing(g,s*.28,-.13,0,.24,.18,-s*.30,c)}}parent.add(g)}
function apply(){localStorage.setItem(KEY,JSON.stringify(state));const root=findCharacter();if(!root){setTimeout(apply,700);return}root.traverse?.(o=>{if(!o.material||o.name?.includes('eye')||o.name?.includes('skin')||o.name?.includes('hair'))return;if(!o.userData.agcbOriginalColor&&o.material.color)o.userData.agcbOriginalColor=o.material.color.getHex();if(o.material.color&&/(dress|outfit|cloth|top|skirt|cat|ear|ribbon|bow)/i.test(o.name||''))o.material.color.setHex(COLORS[state.color])});const old=[];root.traverse?.(o=>{if(o.name==='agcb-wardrobe-back')old.push(o)});old.forEach(o=>o.parent?.remove(o));if(state.back.includes('蝴蝶結'))bow(root,COLORS[state.color],state.back==='特大蝴蝶結');else if(state.back!=='無')wings(root,state.back,COLORS[state.color]);window.dispatchEvent(new CustomEvent('ag-wardrobe-applied',{detail:{...state}}))}
function mount(){if(document.getElementById('agWardrobeBtn'))return;const css=document.createElement('style');css.textContent=`#agWardrobeBtn{position:fixed;z-index:88;right:max(18px,env(safe-area-inset-right));top:max(118px,calc(env(safe-area-inset-top) + 108px));border:3px solid #fff;border-radius:18px;background:#fffde8e8;padding:8px 11px;font-weight:900;color:#42565c;box-shadow:0 3px 12px #0002}#agWardrobe{display:none;position:fixed;z-index:150;inset:0;background:#0005;align-items:center;justify-content:center;padding:16px}#agWardrobe.open{display:flex}#agWardrobeCard{width:min(540px,92vw);max-height:86dvh;overflow:auto;background:#fffaf0;border-radius:22px;padding:16px;color:#3d5556}#agWardrobeCard h2{margin:0 0 12px}.agWRow{margin:12px 0}.agWLabel{font-weight:900;margin-bottom:6px}.agWOptions{display:flex;gap:7px;flex-wrap:wrap}.agWOpt{border:2px solid #e5dccb;border-radius:12px;background:white;padding:8px 10px;font-weight:800}.agWOpt.on{outline:3px solid #ffe06b}.agWClose{float:right;border:0;border-radius:50%;width:38px;height:38px;background:#fff;font-size:22px;font-weight:900}`;document.head.appendChild(css);const btn=document.createElement('button');btn.id='agWardrobeBtn';btn.textContent='👗 衣櫃';document.body.appendChild(btn);const modal=document.createElement('div');modal.id='agWardrobe';modal.innerHTML=`<div id="agWardrobeCard"><button class="agWClose">×</button><h2>👗 衣櫃 <small>${VERSION}</small></h2><div class="agWRow"><div class="agWLabel">貓系列／服裝色系</div><div class="agWOptions" data-k="color"></div></div><div class="agWRow"><div class="agWLabel">腰部蝴蝶結／背部翅膀</div><div class="agWOptions" data-k="back"></div></div></div>`;document.body.appendChild(modal);const sets={color:Object.keys(COLORS),back:BACKS};const render=()=>Object.entries(sets).forEach(([k,arr])=>{const box=modal.querySelector(`[data-k="${k}"]`);box.innerHTML='';arr.forEach(v=>{const b=document.createElement('button');b.className='agWOpt'+(state[k]===v?' on':'');b.textContent=v;b.onclick=()=>{state[k]=v;render();apply()};box.appendChild(b)})});btn.onclick=()=>{render();modal.classList.add('open')};modal.querySelector('.agWClose').onclick=()=>modal.classList.remove('open');modal.onclick=e=>{if(e.target===modal)modal.classList.remove('open')};render();apply()}
window.AGWardrobe={version:VERSION,get:()=>({...state}),set:v=>{state={...state,...v};apply()}};document.readyState==='loading'?document.addEventListener('DOMContentLoaded',mount):mount();
