import fs from 'node:fs/promises';
await import('./build-v0499.mjs');
const src='output/AG_Model003_Adult_Female_Candidate_006.glb';
const dst='output/AG_Model003_Adult_Female_Candidate_007.glb';
const raw=await fs.readFile(src);const dv=new DataView(raw.buffer,raw.byteOffset,raw.byteLength);
if(dv.getUint32(0,true)!==0x46546c67||dv.getUint32(4,true)!==2)throw new Error('not GLB2');
let off=12,json=null,bin=null;while(off<raw.length){const len=dv.getUint32(off,true),type=dv.getUint32(off+4,true),data=raw.subarray(off+8,off+8+len);if(type===0x4e4f534a)json=JSON.parse(data.toString('utf8').trimEnd());if(type===0x004e4942)bin=Buffer.from(data);off+=8+len}if(!json||!bin)throw new Error('missing chunks');
function accessorForNode(nodeName){const ni=json.nodes.findIndex(n=>n.name===nodeName);if(ni<0)throw new Error('node not found '+nodeName);const mi=json.nodes[ni].mesh;if(mi===undefined)throw new Error('node has no mesh '+nodeName);const prim=json.meshes[mi].primitives[0],ai=prim.attributes.POSITION,a=json.accessors[ai],bv=json.bufferViews[a.bufferView];return{a,start:(bv.byteOffset||0)+(a.byteOffset||0),stride:bv.byteStride||12}}
function eachPosition(nodeName,fn){const {a,start,stride}=accessorForNode(nodeName),mn=[Infinity,Infinity,Infinity],mx=[-Infinity,-Infinity,-Infinity];for(let i=0;i<a.count;i++){const p=start+i*stride,x=bin.readFloatLE(p),y=bin.readFloatLE(p+4),z=bin.readFloatLE(p+8),q=fn(x,y,z)||[x,y,z];bin.writeFloatLE(q[0],p);bin.writeFloatLE(q[1],p+4);bin.writeFloatLE(q[2],p+8);for(let k=0;k<3;k++){mn[k]=Math.min(mn[k],q[k]);mx[k]=Math.max(mx[k],q[k])}}a.min=mn;a.max=mx}
for(const s of [-1,1]){const name='ivory-smooth-sleeve-'+s,center=s*.25;eachPosition(name,(x,y,z)=>{let nx=center+(x-center)*.84,nz=z*.86,ny=y;if(y<.82)ny=y+(.82-y)*.56;return[nx,ny,nz]})}
// Soften the diaper-like central trouser bridge without breaking the two animated legs.
eachPosition('light-high-waist-trousers',(x,y,z)=>{let nx=x,ny=y,nz=z;if(y<.61&&Math.abs(x)<.085){const t=(.61-y)/.43;nz=z*(1-.46*Math.min(1,t));nx=x*(1+.28*Math.min(1,t))}if(y>.61&&y<.76){const t=(y-.61)/.15;nx=x*(.97+.05*t)}return[nx,ny,nz]});
// Further reduce helmet effect while retaining side-part fringe and waves.
eachPosition('back-hair-mass',(x,y,z)=>[x*.90,1.43+(y-1.43)*.92,-.092+(z+.092)*.72]);
const js=JSON.stringify(json).replaceAll('Candidate_006','Candidate_007').replaceAll('candidate-006','candidate-007');const jbuf=Buffer.from(js,'utf8'),jpad=(4-jbuf.length%4)%4,jchunk=Buffer.concat([jbuf,Buffer.alloc(jpad,0x20)]),bpad=(4-bin.length%4)%4,bchunk=Buffer.concat([bin,Buffer.alloc(bpad)]),total=12+8+jchunk.length+8+bchunk.length,out=Buffer.alloc(total);let w=0;out.writeUInt32LE(0x46546c67,w);w+=4;out.writeUInt32LE(2,w);w+=4;out.writeUInt32LE(total,w);w+=4;out.writeUInt32LE(jchunk.length,w);w+=4;out.writeUInt32LE(0x4e4f534a,w);w+=4;jchunk.copy(out,w);w+=jchunk.length;out.writeUInt32LE(bchunk.length,w);w+=4;out.writeUInt32LE(0x004e4942,w);w+=4;bchunk.copy(out,w);
await fs.writeFile(dst,out);const manifest={id:'ag-model003-adult-female-candidate-007',status:'INDEPENDENT_CANDIDATE_NOT_GAME_INTEGRATED',bytes:out.length,bones:18,slots:['bodyBase','underlayer','top','bottom','hair','shoes','accessory'],clips:['Idle','Walk','Run','Jump','JointInspection'],appearanceAccepted:false,realDeviceTested:false,gameIntegrated:false,notes:['V0.5.00 appearance refinement over clean V0.4.99 hierarchy.','Sleeves are narrower and raised at cuffs so skin hands can read separately.','Trouser central bridge is visually softened while keeping both animated leg regions.','Rear hair mass is thinner; improved face/fringe are preserved.','Technical validation is not appearance approval.']};await fs.writeFile('output/AG_Model003_Adult_Female_Candidate_007_manifest.json',JSON.stringify(manifest,null,2));console.log(JSON.stringify(manifest));
