import fs from 'node:fs/promises';
await import('./build-v0499.mjs');
const src='output/AG_Model003_Adult_Female_Candidate_006.glb';
const dst='output/AG_Model003_Adult_Female_Candidate_009.glb';
const raw=await fs.readFile(src);const dv=new DataView(raw.buffer,raw.byteOffset,raw.byteLength);
if(dv.getUint32(0,true)!==0x46546c67||dv.getUint32(4,true)!==2)throw new Error('not GLB2');
let off=12,json=null,bin=null;while(off<raw.length){const len=dv.getUint32(off,true),type=dv.getUint32(off+4,true),data=raw.subarray(off+8,off+8+len);if(type===0x4e4f534a)json=JSON.parse(data.toString('utf8').trimEnd());if(type===0x004e4942)bin=Buffer.from(data);off+=8+len}if(!json||!bin)throw new Error('missing chunks');
function accessorForNode(nodeName){const ni=json.nodes.findIndex(n=>n.name===nodeName);if(ni<0)throw new Error('node not found '+nodeName);const mi=json.nodes[ni].mesh;if(mi===undefined)throw new Error('node has no mesh '+nodeName);const prim=json.meshes[mi].primitives[0],ai=prim.attributes.POSITION,a=json.accessors[ai],bv=json.bufferViews[a.bufferView];if(a.componentType!==5126||a.type!=='VEC3')throw new Error('unexpected POSITION '+nodeName);return{a,start:(bv.byteOffset||0)+(a.byteOffset||0),stride:bv.byteStride||12}}
function eachPosition(nodeName,fn){const {a,start,stride}=accessorForNode(nodeName),mn=[Infinity,Infinity,Infinity],mx=[-Infinity,-Infinity,-Infinity];for(let i=0;i<a.count;i++){const p=start+i*stride,x=bin.readFloatLE(p),y=bin.readFloatLE(p+4),z=bin.readFloatLE(p+8),q=fn(x,y,z)||[x,y,z];bin.writeFloatLE(q[0],p);bin.writeFloatLE(q[1],p+4);bin.writeFloatLE(q[2],p+8);for(let k=0;k<3;k++){mn[k]=Math.min(mn[k],q[k]);mx[k]=Math.max(mx[k],q[k])}}a.min=mn;a.max=mx}
function detachNode(name){const ni=json.nodes.findIndex(n=>n.name===name);if(ni<0)return;for(const n of json.nodes){if(Array.isArray(n.children))n.children=n.children.filter(i=>i!==ni)}for(const s of json.scenes||[]){if(Array.isArray(s.nodes))s.nodes=s.nodes.filter(i=>i!==ni)}}
// Coherent sleeveless look: remove the misaligned white sleeve meshes instead of layering them over the skin arms.
detachNode('ivory-smooth-sleeve--1');detachNode('ivory-smooth-sleeve-1');
// Slim only the arm/hand regions of the connected skin body while preserving the original 18-bone rig and pivots.
eachPosition('adult-female-connected-base',(x,y,z)=>{const ax=Math.abs(x);if(ax>.18&&y>.62&&y<1.27){const s=x<0?-1:1;let c=s*.275;if(y<.79)c=s*.315;else if(y>1.08)c=s*.235;const k=y<.79?.80:.70;return[c+(x-c)*k,y,z*(y<.79?.88:.76)]}return[x,y,z]});
// Smaller adult head/face, but keep the neck bone and animation hierarchy unchanged.
const hc=[0,1.535,.012];for(const n of ['adult-female-smooth-head','anime-eye--1','eye-highlight--1','upper-lash--1','brow--1','ear--1','anime-eye-1','eye-highlight-1','upper-lash-1','brow-1','ear-1','nose-tip','soft-smile'])eachPosition(n,(x,y,z)=>[hc[0]+(x-hc[0])*.86,hc[1]+(y-hc[1])*.86,hc[2]+(z-hc[2])*.86]);
// Reduce helmet volume while preserving the long-hair silhouette and face framing.
for(const n of ['hair-cap','side-part-fringe-0','side-part-fringe-1','side-part-fringe-2','side-part-fringe-3','face-frame--1','outer-wave--1','face-frame-1','outer-wave-1'])eachPosition(n,(x,y,z)=>[x*.90,1.535+(y-1.535)*.93,-.01+(z+.01)*.86]);
eachPosition('back-hair-mass',(x,y,z)=>[x*.80,1.42+(y-1.42)*.95,-.092+(z+.092)*.58]);
// Refine the white top into a stronger adult hourglass silhouette, keeping full garment coverage on the torso.
eachPosition('ivory-smooth-fitted-torso',(x,y,z)=>{const waist=Math.exp(-Math.pow((y-.98)/.13,2)),upper=Math.exp(-Math.pow((y-1.16)/.10,2));let fx=1-.15*waist+.035*upper;if(y>1.12)fx*=1.04;let nz=z*(1-.06*waist);if(z>0&&y>1.05&&y<1.22)nz+=.014*Math.sin((y-1.05)/.17*Math.PI);return[x*fx,y,nz]});
// Narrow both trouser legs independently without opening the central bridge.
eachPosition('light-high-waist-trousers',(x,y,z)=>{if(y<.60){const s=x<0?-1:1,c=s*.115;return[c+(x-c)*.80,y,z*.84]}if(y<.76)return[x*.94,y,z*.92];return[x*.96,y,z]});
for(const s of [-1,1]){const c=s*.115;eachPosition('walking-shoe-'+s,(x,y,z)=>[c+(x-c)*.86,y,.09+(z-.09)*.88]);}
const js=JSON.stringify(json).replaceAll('Candidate_006','Candidate_009').replaceAll('candidate-006','candidate-009');const jbuf=Buffer.from(js,'utf8'),jpad=(4-jbuf.length%4)%4,jchunk=Buffer.concat([jbuf,Buffer.alloc(jpad,0x20)]),bpad=(4-bin.length%4)%4,bchunk=Buffer.concat([bin,Buffer.alloc(bpad)]),total=12+8+jchunk.length+8+bchunk.length,out=Buffer.alloc(total);let w=0;out.writeUInt32LE(0x46546c67,w);w+=4;out.writeUInt32LE(2,w);w+=4;out.writeUInt32LE(total,w);w+=4;out.writeUInt32LE(jchunk.length,w);w+=4;out.writeUInt32LE(0x4e4f534a,w);w+=4;jchunk.copy(out,w);w+=jchunk.length;out.writeUInt32LE(bchunk.length,w);w+=4;out.writeUInt32LE(0x004e4942,w);w+=4;bchunk.copy(out,w);
await fs.writeFile(dst,out);const manifest={id:'ag-model003-adult-female-candidate-009',status:'INDEPENDENT_CANDIDATE_NOT_GAME_INTEGRATED',bytes:out.length,bones:18,slots:['bodyBase','underlayer','top','bottom','hair','shoes','accessory'],clips:['Idle','Walk','Run','Jump','JointInspection'],appearanceAccepted:false,realDeviceTested:false,gameIntegrated:false,notes:['V0.5.02 branches from clean V0.4.99 Candidate 006.','Misaligned procedural sleeves are detached to create one coherent sleeveless white-top silhouette instead of doubled sausage arms.','Skin arms/hands are slimmed locally without moving the 18-bone rig or animation pivots.','Head and helmet-like hair volume are further reduced for an adult proportion read.','Waist, trouser legs and shoes are refined without cutting the central trouser bridge.','Technical validation is not appearance approval.']};await fs.writeFile('output/AG_Model003_Adult_Female_Candidate_009_manifest.json',JSON.stringify(manifest,null,2));console.log(JSON.stringify(manifest));
