import fs from 'node:fs/promises';
await import('./build-v0499.mjs');
const src='output/AG_Model003_Adult_Female_Candidate_006.glb';
const dst='output/AG_Model003_Adult_Female_Candidate_008.glb';
const raw=await fs.readFile(src);const dv=new DataView(raw.buffer,raw.byteOffset,raw.byteLength);
if(dv.getUint32(0,true)!==0x46546c67||dv.getUint32(4,true)!==2)throw new Error('not GLB2');
let off=12,json=null,bin=null;while(off<raw.length){const len=dv.getUint32(off,true),type=dv.getUint32(off+4,true),data=raw.subarray(off+8,off+8+len);if(type===0x4e4f534a)json=JSON.parse(data.toString('utf8').trimEnd());if(type===0x004e4942)bin=Buffer.from(data);off+=8+len}if(!json||!bin)throw new Error('missing chunks');
function accessorForNode(nodeName){const ni=json.nodes.findIndex(n=>n.name===nodeName);if(ni<0)throw new Error('node not found '+nodeName);const mi=json.nodes[ni].mesh;if(mi===undefined)throw new Error('node has no mesh '+nodeName);const prim=json.meshes[mi].primitives[0],ai=prim.attributes.POSITION,a=json.accessors[ai],bv=json.bufferViews[a.bufferView];if(a.componentType!==5126||a.type!=='VEC3')throw new Error('unexpected POSITION '+nodeName);return{a,start:(bv.byteOffset||0)+(a.byteOffset||0),stride:bv.byteStride||12}}
function eachPosition(nodeName,fn){const {a,start,stride}=accessorForNode(nodeName),mn=[Infinity,Infinity,Infinity],mx=[-Infinity,-Infinity,-Infinity];for(let i=0;i<a.count;i++){const p=start+i*stride,x=bin.readFloatLE(p),y=bin.readFloatLE(p+4),z=bin.readFloatLE(p+8),q=fn(x,y,z)||[x,y,z];bin.writeFloatLE(q[0],p);bin.writeFloatLE(q[1],p+4);bin.writeFloatLE(q[2],p+8);for(let k=0;k<3;k++){mn[k]=Math.min(mn[k],q[k]);mx[k]=Math.max(mx[k],q[k])}}a.min=mn;a.max=mx}
const headCenter=[0,1.535,.012];const headNodes=['adult-female-smooth-head','anime-eye--1','eye-highlight--1','upper-lash--1','brow--1','ear--1','anime-eye-1','eye-highlight-1','upper-lash-1','brow-1','ear-1','nose-tip','soft-smile'];for(const n of headNodes)eachPosition(n,(x,y,z)=>[headCenter[0]+(x-headCenter[0])*.90,headCenter[1]+(y-headCenter[1])*.90,headCenter[2]+(z-headCenter[2])*.90]);
const hairNodes=['hair-cap','side-part-fringe-0','side-part-fringe-1','side-part-fringe-2','side-part-fringe-3','face-frame--1','outer-wave--1','face-frame-1','outer-wave-1'];for(const n of hairNodes)eachPosition(n,(x,y,z)=>[x*.93,1.535+(y-1.535)*.96,-.01+(z+.01)*.90]);
eachPosition('back-hair-mass',(x,y,z)=>[x*.84,1.42+(y-1.42)*.96,-.092+(z+.092)*.62]);
for(const s of [-1,1]){const center=s*.25;eachPosition('ivory-smooth-sleeve-'+s,(x,y,z)=>[center+(x-center)*.86,y,z*.84]);}
eachPosition('ivory-smooth-fitted-torso',(x,y,z)=>{const waist=Math.exp(-Math.pow((y-.98)/.14,2));const bust=Math.exp(-Math.pow((y-1.14)/.11,2));const fx=1-.11*waist+.025*bust;let nz=z*(1-.05*waist);if(z>0&&y>1.04&&y<1.21)nz+=.010*Math.sin((y-1.04)/.17*Math.PI);return[x*fx,y,nz]});
eachPosition('light-high-waist-trousers',(x,y,z)=>{if(y<.61){const s=x<0?-1:1,c=s*.115;return[c+(x-c)*.86,y,z*.88]}if(y<.76)return[x*.96,y,z*.94];return[x,y,z]});
for(const s of [-1,1]){const c=s*.115;eachPosition('walking-shoe-'+s,(x,y,z)=>[c+(x-c)*.92,y,.09+(z-.09)*.92]);}
const js=JSON.stringify(json).replaceAll('Candidate_006','Candidate_008').replaceAll('candidate-006','candidate-008');const jbuf=Buffer.from(js,'utf8'),jpad=(4-jbuf.length%4)%4,jchunk=Buffer.concat([jbuf,Buffer.alloc(jpad,0x20)]),bpad=(4-bin.length%4)%4,bchunk=Buffer.concat([bin,Buffer.alloc(bpad)]),total=12+8+jchunk.length+8+bchunk.length,out=Buffer.alloc(total);let w=0;out.writeUInt32LE(0x46546c67,w);w+=4;out.writeUInt32LE(2,w);w+=4;out.writeUInt32LE(total,w);w+=4;out.writeUInt32LE(jchunk.length,w);w+=4;out.writeUInt32LE(0x4e4f534a,w);w+=4;jchunk.copy(out,w);w+=jchunk.length;out.writeUInt32LE(bchunk.length,w);w+=4;out.writeUInt32LE(0x004e4942,w);w+=4;bchunk.copy(out,w);
await fs.writeFile(dst,out);const manifest={id:'ag-model003-adult-female-candidate-008',status:'INDEPENDENT_CANDIDATE_NOT_GAME_INTEGRATED',bytes:out.length,bones:18,slots:['bodyBase','underlayer','top','bottom','hair','shoes','accessory'],clips:['Idle','Walk','Run','Jump','JointInspection'],appearanceAccepted:false,realDeviceTested:false,gameIntegrated:false,notes:['V0.5.01 branches from clean V0.4.99 Candidate 006, not the regressed V0.5.00 geometry.','Head and hair volume are reduced to push the silhouette toward adult proportions without moving the 18-bone rig.','Sleeves are narrowed without shortening so upper-arm skin remains covered.','Trouser legs are narrowed around each leg axis without cutting the central bridge.','Torso waist is refined while preserving garment coverage.','Technical validation is not appearance approval.']};await fs.writeFile('output/AG_Model003_Adult_Female_Candidate_008_manifest.json',JSON.stringify(manifest,null,2));console.log(JSON.stringify(manifest));
