// AG Cute Blocks V0.5.111 — TEST-only Google Apps Script Drive backup/history endpoint.
// PROD write/read disabled. Restore/Delete remain disabled server-side; restore uses verified TEST READBACK client-side.
const AGCB_VERSION='0.5.111';
const AGCB_PROJECT='AG Cute Blocks';
const AGCB_CONTRACT='AG_CUTE_BLOCKS_DRIVE_BACKUP_V1';
const AGCB_FORMAT='AG_CUTE_BLOCKS_SAVE_ENVELOPE';
const AGCB_TEST_FOLDER_ID='1XTOj_YbpfehI4hIjhaKBPw3oI_L3HEpZ';
const AGCB_PROD_FOLDER_ID='19YNP7hM7O0XevxiCvLsuiy65woggBs3R';
const AGCB_TEST_PATH='AG Cute Blocks/SAVE/TEST';
const AGCB_PROD_PATH='AG Cute Blocks/SAVE/PROD';
const AGCB_TEST_WRITE_ENABLED=true;
const AGCB_PROD_WRITE_ENABLED=false;
const AGCB_TOKEN_PROPERTY='AGCB_BRIDGE_TOKEN';
function agcbJson_(value){return ContentService.createTextOutput(JSON.stringify(value)).setMimeType(ContentService.MimeType.JSON)}
function doGet(){return agcbJson_({ok:true,project:AGCB_PROJECT,version:AGCB_VERSION,status:'TEST_BRIDGE_READY',prodWriteEnabled:false,prodReadEnabled:false,restoreEnabled:false,deleteEnabled:false,historyListEnabled:true})}
function agcbFail_(reason){return{ok:false,reason:String(reason||'rejected')}}
function agcbToken_(){return String(PropertiesService.getScriptProperties().getProperty(AGCB_TOKEN_PROPERTY)||'')}
function agcbAuth_(payload){const expected=agcbToken_();if(expected.length<32)throw new Error('server-token-not-configured');if(String(payload&&payload.authToken||'')!==expected)throw new Error('unauthorized')}
function agcbCanonical_(b){return JSON.stringify({project:b.project,format:b.format,schema:b.schema,saveSchema:b.saveSchema,environment:b.environment,gameVersion:b.gameVersion,createdAt:b.createdAt,source:b.source,requiredKeys:b.requiredKeys,missingRequired:b.missingRequired,records:b.records})}
function agcbSha256_(text){const bytes=Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,String(text),Utilities.Charset.UTF_8);return bytes.map(function(b){const n=(b<0?b+256:b);return('0'+n.toString(16)).slice(-2)}).join('')}
function agcbValidateEnvelope_(bundle,env){if(!bundle||bundle.project!==AGCB_PROJECT||bundle.format!==AGCB_FORMAT)throw new Error('invalid-save-envelope');if(String(bundle.environment||'').toUpperCase()!==env)throw new Error('envelope-environment-mismatch');if(!bundle.integrity||bundle.integrity.algorithm!=='SHA-256'||!bundle.integrity.sha256)throw new Error('integrity-missing');const actual=agcbSha256_(agcbCanonical_(bundle));if(actual!==bundle.integrity.sha256)throw new Error('integrity-mismatch');return actual}
function agcbSafeFileName_(name,env){const value=String(name||'');if(!value||value.indexOf('/')>=0||value.indexOf('\\')>=0||!value.endsWith('.json'))throw new Error('invalid-file-name');if(value.indexOf(AGCB_PROJECT+'_'+env+'_')!==0)throw new Error('file-name-environment-mismatch');return value}
function agcbFolderContains_(folder,file){const parents=file.getParents();while(parents.hasNext())if(parents.next().getId()===folder.getId())return true;return false}
function agcbBackup_(payload){const request=payload.request||{};if(request.contract!==AGCB_CONTRACT||request.project!==AGCB_PROJECT)throw new Error('invalid-contract');const env=String(request.environment||'').toUpperCase();if(env!=='TEST')throw new Error(env==='PROD'?'prod-write-disabled':'invalid-save-environment');if(!AGCB_TEST_WRITE_ENABLED||AGCB_PROD_WRITE_ENABLED)throw new Error('unsafe-server-write-policy');if(request.destinationPath!==AGCB_TEST_PATH)throw new Error('destination-path-mismatch');if(['LATEST','HISTORY','PRE_UPDATE'].indexOf(String(request.role||''))<0)throw new Error('invalid-backup-role');const name=agcbSafeFileName_(request.fileName,env);const sha=agcbValidateEnvelope_(request.envelope,env);const folder=DriveApp.getFolderById(AGCB_TEST_FOLDER_ID);const file=folder.createFile(name,JSON.stringify(request.envelope),MimeType.PLAIN_TEXT);try{const saved=JSON.parse(file.getBlob().getDataAsString('UTF-8'));const readSha=agcbValidateEnvelope_(saved,'TEST');if(readSha!==sha)throw new Error('remote-sha256-mismatch');return{ok:true,fileId:file.getId(),receiptId:file.getId(),environment:'TEST',sha256:sha}}catch(err){file.setTrashed(true);throw err}}
function agcbReadback_(payload){const env=String(payload.environment||'').toUpperCase();if(env!=='TEST')throw new Error(env==='PROD'?'prod-read-disabled':'invalid-save-environment');const id=String(payload.fileId||payload.receiptId||'');if(!id)throw new Error('file-id-required');const folder=DriveApp.getFolderById(AGCB_TEST_FOLDER_ID);const file=DriveApp.getFileById(id);if(!agcbFolderContains_(folder,file))throw new Error('file-outside-test-folder');const envelope=JSON.parse(file.getBlob().getDataAsString('UTF-8'));const sha=agcbValidateEnvelope_(envelope,'TEST');return{ok:true,fileId:id,receiptId:id,environment:'TEST',fileName:file.getName(),sha256:sha,envelope:envelope}}
function agcbListHistory_(payload){const env=String(payload.environment||'').toUpperCase();if(env!=='TEST')throw new Error(env==='PROD'?'prod-read-disabled':'invalid-save-environment');const folder=DriveApp.getFolderById(AGCB_TEST_FOLDER_ID);const files=folder.getFiles();const rows=[];while(files.hasNext()){const f=files.next();const name=f.getName();if(name.indexOf(AGCB_PROJECT+'_TEST_')!==0||!name.endsWith('.json'))continue;rows.push({fileId:f.getId(),fileName:name,updatedAt:f.getLastUpdated().toISOString(),size:f.getSize()})}rows.sort(function(a,b){return a.updatedAt<b.updatedAt?1:a.updatedAt>b.updatedAt?-1:0});return{ok:true,environment:'TEST',items:rows.slice(0,30),count:rows.length}}
function doPost(e){try{const payload=JSON.parse(String(e&&e.postData&&e.postData.contents||'{}'));agcbAuth_(payload);const action=String(payload.action||'').toUpperCase();if(action==='BACKUP')return agcbJson_(agcbBackup_(payload));if(action==='READBACK')return agcbJson_(agcbReadback_(payload));if(action==='LIST_HISTORY')return agcbJson_(agcbListHistory_(payload));return agcbJson_(agcbFail_('unsupported-action'))}catch(err){return agcbJson_(agcbFail_(err&&err.message||err))}}
function agcbSetupTestBridge_(){const props=PropertiesService.getScriptProperties();let token=String(props.getProperty(AGCB_TOKEN_PROPERTY)||'');let created=false;if(token.length<32){token=(Utilities.getUuid()+Utilities.getUuid()).replace(/-/g,'');props.setProperty(AGCB_TOKEN_PROPERTY,token);created=true}const testFolder=DriveApp.getFolderById(AGCB_TEST_FOLDER_ID);if(testFolder.getName()!=='TEST')throw new Error('test-folder-id-name-mismatch');return{project:AGCB_PROJECT,version:AGCB_VERSION,environment:'TEST',created:created,token:token,tokenLength:token.length,testFolderId:AGCB_TEST_FOLDER_ID,testPath:AGCB_TEST_PATH,prodWriteEnabled:false,prodReadEnabled:false,restoreEnabled:false,deleteEnabled:false,historyListEnabled:true}}
function agcbGetSetupStatus_(){const token=agcbToken_();return{project:AGCB_PROJECT,version:AGCB_VERSION,environment:'TEST',tokenConfigured:token.length>=32,testFolderId:AGCB_TEST_FOLDER_ID,testPath:AGCB_TEST_PATH,prodWriteEnabled:false,prodReadEnabled:false,restoreEnabled:false,deleteEnabled:false,historyListEnabled:true}}
function agcbDeploymentPreflight_(){const token=agcbToken_();const testFolder=DriveApp.getFolderById(AGCB_TEST_FOLDER_ID);const prodFolder=DriveApp.getFolderById(AGCB_PROD_FOLDER_ID);const result={project:AGCB_PROJECT,version:AGCB_VERSION,status:'DEPLOYMENT_PREFLIGHT_PASS',environment:'TEST',tokenConfigured:token.length>=32,testFolderOk:testFolder.getName()==='TEST',prodFolderVisible:!!prodFolder.getId(),testWriteEnabled:AGCB_TEST_WRITE_ENABLED,prodWriteEnabled:AGCB_PROD_WRITE_ENABLED,prodReadEnabled:false,restoreEnabled:false,deleteEnabled:false,historyListEnabled:true};if(!result.tokenConfigured)throw new Error('server-token-not-configured');if(!result.testFolderOk)throw new Error('test-folder-id-name-mismatch');if(result.prodWriteEnabled)throw new Error('unsafe-prod-write-enabled');return result}
function agcbSetupTestBridge(){return agcbSetupTestBridge_()}
function agcbDeploymentPreflight(){return agcbDeploymentPreflight_()}
